### ISSUE TITLE
sconti e spese di trasporto variabili

### ISSUE THREAD

**Issue by madbob** [madbob/GASdottoNG#100]
Strutturare sconti e spese di trasporto per avere soglie dinamicamente calcolate, in numero arbitrario,  in misura assoluta o percentuale, su quantita' prenotata, costo complessivo o peso complessivo (dipende da #98 ).
Assegnare questo attributo ai singoli prodotti, agli ordini, ai fornitori (per usarlo come default per i suoi ordini) ed ai luoghi di consegna.

**Comment by madbob** [comment]
@pcdevoti l'idea sarebbe quella di rimpiazzare le attuali spese di trasporto e gli sconti con delle "trasformazioni" dinamicamente configurabili (come i tipi di movimento contabile) da poter applicare distintamente ai prodotti, agli ordini (prendendo dei default assegnati ai rispettivi fornitori) e ai luoghi di consegna, di cui specificare:
- se vanno considerate sul singolo elemento o collettivamente su tutto l'ordine (e.g. prodotto X, sconto di 3 euro se il singolo utente ne acquista almeno 3, sconto del 10% se collettivamente ne vengono acquistati almeno 30)
- l'eventuale criterio di distribuzione su tutto l'ordine (in base alla quantita', al prezzo, o - prossimamente - al peso #98 )
- le soglie, con il relativo valore - assoluto o percentuale - da applicare al costo dell'elemento (e.g. se il peso collettivo delle prenotazioni all'ordine è inferiore a 10 chili costa X di trasporto, se è inferiore a 20 chili costa Y, eccetera)
- l'ordine con cui applicare eventuali trasformazioni multiple su un ordine che ne contempla diverse (e.g. prima applico lo sconto X sulla prenotazione, e poi aggiungo il 5% di spese di trasporto per il luogo di consegna Y)

Usando delle generiche trasformazioni per rappresentare spese di trasporto e sconti sarebbe anche possibile averne altre, arbitrarie, tipo delle raccolte fondi (e.g. aggiungi 1 euro a tutte le prenotazioni di quest'ordine per fare una donazione al Burkina Faso) o il mantenimento delle spese di gestione del gruppo (modalita' usata da GASTorino e altri, percui viene aggiunto un X% trasversale alle prenotazioni).

L'estensione di queste dinamiche ai singoli luoghi di consegna era gia' emersa in passato con GASTorino, ed e' tornata in auge adesso (adesso che sono tutti chiusi a casa diversi fornitori fanno consegne a domicilio, con costi differenziati a seconda della distanza).

Pareri?

**Comment by Cjto79** [comment]
Ottima idea...
