### ISSUE TITLE
recupero ordini archiviati in gestione fatture e ricevute

### ISSUE THREAD

**Issue by madbob** [madbob/GASdottoNG#101]
Permettere di ripescare ordini gia' archiviati dalla gestione di fatture e ricevute. L'auspicio e' quello di farli archiviare subito e non farli accumulare per mesi (rallentando enormemente la schermata degli ordini).

**Comment by madbob** [comment]
La soluzione più rapida è quella di visualizzare, in fase di selezione degli ordini coinvolti in una fattura, tutti gli ordini del fornitore consegnati o archiviati nell'ultimo anno (anziché solo quelli marcati come consegnati). @pcdevoti per te è ragionevole?

**Comment by pcdevoti** [comment]
In alcuni casi gli ordini archiviati possono essere tanti. Bisogna visualizzare solo quelli per i quali non è registrata la data di pagamento.
