### ISSUE TITLE
info consegna nella mail di apertura d'ordine

### ISSUE THREAD

**Issue by ottimodorfmeinster** [madbob/GASdottoNG#103]
Ciao,
creata la consegna dal Menù/Configurazioni/Luogo di Consegna, potrebbe essere interessante, qualora data e ora della consegna fossero certe, inserire la comunicazione all'interno della mail di apertura dell'ordine! E' un buona pratica far conoscere al gasista in anticipo dove verrà consegnata la merce. Riepilogando. Associare in fase di apertura d'ordine già una consegna precedentemente creata e allegarla alla mail di apertura d'ordine!

**Comment by madbob** [comment]
Temo che sia stato travisato l'uso dei "Luoghi di Consegna": e' una funzione pensata per distribuire le consegne in piu' posti, in caso di GAS distribuiti geograficamente; una volta definiti i diversi luoghi ciascun utente puo' selezionare quello che preferisce e a posteriori e' possibile esportare i dettagli sulle prenotazioni suddivisi appunto per destinazione (in modo da sapere quale parte di ciascun ordine va da una parte o dall'altra).

**Comment by Cjto79** [comment]
Anche questo va bene. Sarebbe meglio implementare la funzione di cui ho accennato.
Ogni produttore ha un referente interno nel G.A.S. che decide autonomamente o in accordo con il produttore dove effettuare la consegna! Molte volte è a casa del referente, altre volte in spazi diversi per la gestione degli ordini INTERGAS! Ripeto che è buona pratica far conoscere al gasista in anticipo dove verrà consegnata la merce. Allegare alla mail di apertura d'ordine il luogo di consegna, sarebbe un'importante rivoluzione! 
Parliamone!

**Comment by pcdevoti** [comment]
Non capisco il problema. Il luogo di consegna è associato all'utente e la data di consegna può essere definita al momento dlel'apertura dell'ordine. Non esiste una funzione di creazione di una consegna

**Comment by madbob** [comment]
Eviterei di usare i "Luoghi di Consegna" anche per questo caso (alla fine si rischia di fare solo una gran confusione), semmai si possono usare i gia' esistenti commenti assegnabili agli ordini (e agli aggregati) per veicolare informazioni addizionali come appunto il luogo previsto per la consegna.

**Comment by ottimodorfmeinster** [comment]
La mia richiesta è quella di far comparire nel testo della mail dell'apertura d'ordine, il luogo di consegna. Ma questa cosa non si può fare perché non è possibile associare il luogo di consegna a un ordine specifico. O meglio, da quello che sono riuscito a capire, il 'Luogo di Consegna' è stato pensato solo per il fornitore. Potrebbe essere utile...
Questi screenshots dimostrano come l'utente/gasista non riesce mai a visualizzare dove avverrà la consegna dei prodotti.
![Screenshot_2020-04-26 Bio C'è GASdotto(2)](https://user-images.githubusercontent.com/63597956/80300746-8cccc000-879f-11ea-809b-bbba6f3a1b62.png)
![Screenshot_2020-04-26 Bio C'è GASdotto(1)](https://user-images.githubusercontent.com/63597956/80300749-8fc7b080-879f-11ea-90dc-49e1c53c65ff.png)
![Screenshot_2020-04-26 Bio C'è GASdotto](https://user-images.githubusercontent.com/63597956/80300752-90f8dd80-879f-11ea-8368-61233e682358.png)
In quest'altro esempio l'utente/gasista, questa volta referente, non riesce a visualizzare il luogo di consegna. Non ricordo se nella mail di riepilogo compare il luogo di consegna.....
![Screenshot_2020-04-26 Bio C'è GASdotto(3)](https://user-images.githubusercontent.com/63597956/80300810-167c8d80-87a0-11ea-9ff1-2a42f5fd4557.png)

**Comunque, ho un problema nella visualizzazione dei pdf dei 'Dettagli di Consegna' ad ordine chiuso. Non riesco a visualizzare gli ordinativi delle persone!**

**Comment by pcdevoti** [comment]
Il suggerimento è di inserire l'indirizzo di consegna nel campo Commento dell'ordine. In questo modo l'indormazione compare sempre a fiando del numero dell'ordine.
Per il problema del Dettaglio consegne magari scrivimi privatamente e vediamo di risolverlo, per noi funziona regolarmente.
Mi puoi scrivere a piercarlo.devoti@gmail.com
