### ISSUE TITLE
visualizzazioni ordini in sola lettura da parte di semplici gasisti

### ISSUE THREAD

**Issue by Cjto79** [madbob/GASdottoNG#104]
Potrebbe essere utile la visualizzazione in sola lettura, da parte di singoli/semplici gasisti, degli ordini degli altri componenti del G.A.S. Questo permetterebbe alle persone di farsi un'idea di quanto è stato ordinato e contribuire maggiormente, qualora c'è ne fosse bisogno, all'ordine.
Mi spiego meglio. Molti ordini hanno bisogno di raggiungere un certo importo! Dando a tutti la possibilità di visualizzare costantemente l'importo totale dell'ordine, qualora l'ordine non raggiunga l'importo previsto, ogni persona potrebbe contribuire al suo raggiungimento....

**Comment by madbob** [comment]
Questo è stato introdotto recentemente: è sufficiente abilitare il nuovo permesso "Vedere tutti gli ordini" per il ruolo Utente, in Configurazioni -> Permessi.
