### ISSUE TITLE
Errore Download - Listini CSV

### ISSUE THREAD

**Issue by ottimodorfmeinster** [madbob/GASdottoNG#108]
Ciao. Non funziona la funzione download listini in formato .csv
É possibile eliminare tutti i prodotti di un fornitore  in un 'colpo' solo? 
Ciao e grazie
![Screenshot_2020-05-11 414 Request-URI Too Large(1)](https://user-images.githubusercontent.com/63597956/81540651-3dc38500-9372-11ea-8c7e-b41066c50309.png)

**Comment by madbob** [comment]
Per il download: prova adesso. Evidentemente era un listino molto grande che ha raggiunto alcuni limiti preimpostati sul server, li ho alzati un po' adesso.
Per l'eliminazione dei prodotti: no, non c'e' un modo, anche perche' sarebbe ovviamente una operazione pericolosa e poco desiderabile.

**Comment by ottimodorfmeinster** [comment]
Ciao. Ancora errore, forse i limiti vanno alzati ancora! Si, è un listino abbastanza importate! 
Grazie.

**Comment by frascare75** [comment]
Ciao, 
anche noi riscontriamo questo problema.
Purtroppo per listini di una certa dimensione , l'esportazione invocata in GET genera l'errore
414 Request-URI Too Long/Large , che non è fixabile sotto apache 2.4 o ngix ( si può solo limitare in basso e non il alto il valore  anche per quesitoni di sicurezza)

Credo che la soluzione più semplice sia convertire in POST la richiesta che viene fatta ( non so quanto sia semplice nel codice ovviamente)

**Comment by madbob** [comment]
Ho semplificato il download dei listini, eliminando il filtro sui prodotti (che generava la lista infinita di parametri passati al server).
cfr. d65ef9a59a6dd45e190e1224381ea94b9aab8c5b
Online al prossimo aggiornamento.
