### ISSUE TITLE
MAIL DI APERTURA ORDINE ANTICIPA LA REALE APERTURA DI UN ORDINE

### ISSUE THREAD

**Issue by ottimodorfmeinster** [madbob/GASdottoNG#109]
Ciao. Ho notato che la mail di apertura di un ordine arriva nel momento i cui crei un ordine anche se imposti un data diversa! Da questo screeshot si evince quanto detto. Ho impostato l'apertura dell'ordine per domani, ma la mail è partita oggi pomeriggio! Errore o voluto?
![Screenshot_2020-05-13 Bio C'è GASdotto](https://user-images.githubusercontent.com/63597956/81831589-d22e1300-953d-11ea-84a0-b95446511d5a.png)
Buon lavoro
Ciro

**Comment by madbob** [comment]
La mail viene inviata quanto lo stato è settato a "Prenotazioni Aperte", a prescindere dalla sua data di apertura (che serve più per chi gestisce gli ordini).
