### ISSUE TITLE
Automatizzare invio email riepilogo e dettaglio consegne a chiusura prenotazione

### ISSUE THREAD

**Issue by frascare75** [madbob/GASdottoNG#111]
Credo sia una funzionalità molto utile date la possibilità di schedulare l'invio automatico del dettaglio
consegne ai partecipanti di una certa prenotazione e soprattutto generare in automatico la mail del riepilogo all'indirizzo email del fornitore ( se impostato) . SI potrebbe settare la funzionalità o nelle configurazioni generali oppure a livello di singolo ordine , in fase di apertura

**Comment by madbob** [comment]
Aggiunto in 06a34b9979199ee300d44e3aac733c1203102605.
Nel pannello Configurazioni -> E-Mail è possibile abilitare sia l'invio dei riepiloghi che la mail al fornitore.
