### ISSUE TITLE
Request-URI Too Long  esportando il listino Prodotti  csv

### ISSUE THREAD

**Issue by frascare75** [madbob/GASdottoNG#112]
Purtroppo per listini di una certa dimensione , l'esportazione invocata in GET genera l'errore
414 Request-URI Too Long , che non è fixabile sotto apache 2.4 ( si può solo limitare in basso e non il alto il valore di LimitRequestLine  , anche per quesitoni di sicurezza) 

Credo che la soluzione più semplice sia convertire in POST la richiesta che viene fatta

**Comment by frascare75** [comment]
duplicato

**Comment by pcdevoti** [comment]
Non ho modo di testare se adesso funziona
