### ISSUE TITLE
Impossibile aggiungere o modificare variante prodotto

### ISSUE THREAD

**Issue by ptiozzo** [madbob/GASdottoNG#115]
Ciao

Da qualche giorno mi sono reso conto che non è possibile modificare o aggiungere nuove varianti

Ho provato con Safari, Chrome e Firefox su macOS su gaschiccodigrano.gasdotto.net

Grazie
Paolo

**Comment by madbob** [comment]
Non riesco a riprodurlo. Hai attivato la Differenza Prezzo? Che valori stai provando a mettere?

**Comment by ptiozzo** [comment]
Grazie @madbob Adesso funziona di nuovo

Comunque si, impostavo anche la differenza di prezzo
