### ISSUE TITLE
Spese trasporto

### ISSUE THREAD

**Issue by ptiozzo** [madbob/GASdottoNG#116]
Ciao
Le spese di trasporto sono suddivise in base all'ordinato e non in base al consegnato.
Se alcuni prodotti non vengono spediti perché non più disponibili finisce che pago le spese di trasporto in maniera non corretta

**Comment by pcdevoti** [comment]
Ciao Paolo,

Se l’importo del trasporto è espresso in €, la ripartizione avviene sulla base del prenotato; per ripartirlo sulla base del consegnato sarebbe necessario un doppio passaggio (finché la consegna non è completata non è possibile avere l’importo effettivo del consegnato) ed è stato deciso, al momento, di non complicare le cose.

Nel caso sia noto il mancato arrivo di alcuni prodotti è possibile procedere in due modi per ovviare al problema dell’errata ripartizione del costo del trasporto:

*	Eliminare dall’ordine i prodotti non arrivati, prima di procedere con la consegna: funziona se qualche prodotto manca completamente; se invece si tratta di arrivi parziali il problema rimane
*	Calcolare manualmente l’incidenza % del trasporto sul totale della merce effettivamente arrivata e specificare il trasporto in % anziché in €; in questo caso il calcolo viene effettuato sul consegnato e non sul prenotato

Spero di aver risposto esaurientemente alla tua domanda; se ci sono dubbi, fammelo sapere.

 

Saluti,

Pier Carlo

 

Da: ptiozzo <notifications@github.com> 
Inviato: mercoledì 19 agosto 2020 16:08
A: madbob/GASdottoNG <GASdottoNG@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: [madbob/GASdottoNG] Spese trasporto (#116)

 

Ciao
Le spese di trasporto sono suddivise in base all'ordinato e non in base al consegnato.
Se alcuni prodotti non vengono spediti perché non più disponibili finisce che pago le spese di trasporto in maniera non corretta
