### ISSUE TITLE
Mail di apertura ordini

### ISSUE THREAD

**Issue by ottimodorfmeinster** [madbob/GASdottoNG#118]
Ciao e buon anno. Sono un pò arrugginito nell'uso del software. Quando parte la mail dell'ordine ai gasisti? Ho appena aperto un ordini che data di oggi. Ma la mail non è partita.
Che si fa?
Grazie 
Ciro

**Comment by madbob** [comment]
1) e' stato sistemato ieri un bug sulle date degli ordini, dovrebbe aver avuto effetto solo sulla loro visualizzazione ma non escludo possa aver disturbato anche altro
2) le notifiche vengono spedite solo quando un ordine e' in stato "aperto"
3) le notifiche sui nuovi ordini vengono inviate solo agli utenti che le hanno esplicitamente abilitate per il fornitore coinvolto (da Pannello Personale -> Notifiche) oppure indistintamente a tutti se e' stato attivato Configurazioni -> E-Mail -> Tutte le notifiche per i nuovi ordini

**Comment by silsalsilsal** [comment]
ciao! noi da qualche tempo non riceviamo le email automatiche di apertura ordine.
Configurazioni -> E-Mail -> Tutte le notifiche per i nuovi ordini è attivo.
Forse è un disturbo legato a questo bug che avete sistemato? Avete ricevuto altre segnalazioni a riguardo?
Silvia

**Comment by madbob** [comment]
@silsalsilsal non credo ci siano correlazioni tra quel bug e le email, e dai pannelli di monitoraggio risulta che le mail escono regolarmente ed abbondantemente.

Forse finiscono nello spam? Se crei una nuova notifica attivando anche l'invio email, arriva?

**Comment by silsalsilsal** [comment]
Abbiamo fatto delle prove, la notifica la ricevono tuttie, mentre le email di apertura ordini non tuttie, ma solo da qualche tempo, mentre prima di gennaio (su per giù) si. Calcola che neanche io le ricevo. C'è qualche impostazione che dovrei controllare? a parte quella di: Configurazioni -> E-Mail -> Tutte le notifiche per i nuovi ordini - che sia attivo.
Siamo lacomunedelcrocicchio, non so se serve saperlo. O chi pensi possa aiutarmi? È la prima volta che chiedo aiuto perché bene o male ci siamo giostrati a impostare e capire il funzionamento con test e varie.
Grazie!
silvia

**Comment by pcdevoti** [comment]
Ciao Silvia,

Sulla questione specifica non so aiutarti e lascio la palla a Bob; più in generale però, se avete dei dubbi su come usare GASdotto non esitare a scrivermi direttamente.

Sono la persona che, insieme a Bob, ha “inventato” GASdotto 13 anni fa (anche se non ne ho scritto neppure una riga di codice)  e il nostro GAS lo usa da sempre.

Ciao,

Pier Carlo

GAS Roccafranca

 

 

Da: silsalsilsal <notifications@github.com> 
Inviato: lunedì 25 gennaio 2021 13:27
A: madbob/GASdottoNG <GASdottoNG@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: Re: [madbob/GASdottoNG] Mail di apertura ordini (#118)

 

Abbiamo fatto delle prove, la notifica la ricevono tuttie, mentre le email di apertura ordini non tuttie, ma solo da qualche tempo, mentre prima di gennaio (su per giù) si. Calcola che neanche io le ricevo. C'è qualche impostazione che dovrei controllare? a parte quella di: Configurazioni -> E-Mail -> Tutte le notifiche per i nuovi ordini - che sia attivo.
Siamo lacomunedelcrocicchio, non so se serve saperlo. O chi pensi possa aiutarmi? È la prima volta che chiedo aiuto perché bene o male ci siamo giostrati a impostare e capire il funzionamento con test e varie.
Grazie!
silvia

**Comment by silsalsilsal** [comment]
Grazie, me lo ricorderò. Lo trovo un ottimo strumento ;) avevamo avuto alcuni dubbi riguardo il multigas, pensavamo di poterlo usare in un certo modo ma non era programmato per quell'uso. Come ti contatto direttamente qualora volessi parlare di questo?
Intanto invece, su questo problema mail aspetto un segnale da Bob.
Grazie comunque,
silvia

**Comment by pcdevoti** [comment]
Scrivimi pure su piercarlo.devoti@gmail.com <mailto:piercarlo.devoti@gmail.com> , poi se necessario ci sentiamo.

 

Ciao,

Pier Carlo

 

 

Da: silsalsilsal <notifications@github.com> 
Inviato: lunedì 25 gennaio 2021 20:20
A: madbob/GASdottoNG <GASdottoNG@noreply.github.com>
Cc: pcdevoti <piercarlo.devoti@gmail.com>; Comment <comment@noreply.github.com>
Oggetto: Re: [madbob/GASdottoNG] Mail di apertura ordini (#118)

 

Grazie, me lo ricorderò. Lo trovo un ottimo strumento ;) avevamo avuto alcuni dubbi riguardo il multigas, pensavamo di poterlo usare in un certo modo ma non era programmato per quell'uso. Come ti contatto direttamente qualora volessi parlare di questo?
Intanto invece, su questo problema mail aspetto un segnale da Bob.
Grazie comunque,
silvia

**Comment by madbob** [comment]
Sistemato: probabilmente un bug introdotto con un aggiornamento o di PHP o di MariaDB sul server...

Per quanto concerne la modalita' MultiGAS: di fatto non sono mai riuscito ad interagire con qualcuno che la usasse per davvero, dunque di fatto non e' mai stata completata, rifinita e testata. Se vi puo' interessare usarla, possiamo sentirci per capire qual e' il vostro caso d'uso e quali sono i limiti che avete riscontrato.

**Comment by silsalsilsal** [comment]
Grazie, ho ricevuto la mail di apertura, evviva! Per MultiGAS possiamo scriverti personalmente quando siamo pronti a riaffrontare l'argomento o apro un ISSUE qui?

**Comment by madbob** [comment]
@silsalsilsal quando vuoi, mandami una mail a bob@linux.it e semmai ci sentiamo una volta. Proprio stasera tengo una call con un altro gruppo che ha questa medesima esigenza, magari ne salta fuori qualcosa di utile anche per voi.
