### ISSUE TITLE
Profilo Utente _ Username

### ISSUE THREAD

**Issue by silsalsilsal** [madbob/GASdottoNG#121]
Da qualche tempo se vado a inserire o modificare un elemento ad un profilo esistente, tipo una e-mail, non mi fa salvare e anzi sottolinea la casella dello username e mi dice: _inserire un valore nel formato richiesto_. ; ma dove è specificato il formato preciso?
Sono cambiate le specifiche per lo username? Non va bene più lo spazio?
Io impostai gli username tutti quanti con nome(spazio)cognome, e già tantx gasistx chiedono assistenza perché non si ricordano la password e/o lo username, se fossero cambiate le specifiche sarebbe un bello sbatti ^_^
Grazie,
silvia

--

domanda laterale. Ogni tanto accumulo degli issues. Poi alcuni li dimentico.
In caso, ne apro uno per ogni tema? È meglio così, così sono rintracciabili e chiudibili, o vi faccio impazzire così?

**Comment by madbob** [comment]
In effetti si, a dicembre avevo introdotto un pattern che forza i caratteri ammessi nello username e tra questi non c'era lo spazio. L'ho reintrodotto adesso (e spero di non averlo tolto all'epoca per qualche motivo specifico...).

Per le issue: si, meglio una distinta per ogni tema. Grazie!

**Comment by silsalsilsal** [comment]
grazie!!!
