### ISSUE TITLE
Automatizzare apertura ordini

### ISSUE THREAD

**Issue by lucagamerro** [madbob/GASdottoNG#122]
GasQueMais ha ordini di fresco che apre ogni settimana.
Sarebbe utile una funzione che permetta di abilitare in automatico l'apertura e la chiusura, ogni settimana, magari con una data di scadenza dell'automatismo.

**Comment by madbob** [comment]
Introdotto in commit dfabff1f734afbfe2218c3baa8e810cb485ca2e9.
In fase di test.
