### ISSUE TITLE
MAIL ORDINI NON PARTONO

### ISSUE THREAD

**Issue by ottimodorfmeinster** [madbob/GASdottoNG#125]
Ciao. Per la seconda volta, non vengono inviate le mail per gli ordini. Possiamo risolvere questo problema.
Grazie

**Comment by madbob** [comment]
Ho apportato adesso qualche modifica: fammi sapere se funziona.

**Comment by ottimodorfmeinster** [comment]
Niente da fare. La mail non parte!

**Comment by madbob** [comment]
Ok, ora direi che e' a posto.
