### ISSUE TITLE
Creare permesso specifico per caricamento fatture

### ISSUE THREAD

**Issue by ptiozzo** [madbob/GASdottoNG#126]
Per il nostro GAS sarebbe comodo fornire un permesso specifico per i referenti per poter caricare le fatture in contabilità

Sarebbe comodo avere un permesso specifico senza far vedere tutta la contabilità

Grazie

**Comment by pcdevoti** [comment]
Mi sembra un po’ complicato: se gli permetti di caricarle dovresti anche permettergli di modificarle il che inevitabilmente ha impatto sulla contabilità.

 

Da: ptiozzo ***@***.***> 
Inviato: martedì 9 marzo 2021 15:59
A: madbob/GASdottoNG ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [madbob/GASdottoNG] Creare permesso specifico per caricamento fatture (#126)

 

Per il nostro GAS sarebbe comodo fornire un permesso specifico per i referenti per poter caricare le fatture in contabilità

Sarebbe comodo avere un permesso specifico senza far vedere tutta la contabilità

Grazie
