### ISSUE TITLE
cambiare password superadmin

### ISSUE THREAD

**Issue by giafaweb** [madbob/GASdottoNG#129]
Abbiate pazienza ... non so se questo è il posto giusto.
Ho installato gasdotto nel server che ospita i nostri siti
lo ho fatto ormai due o tre anni fa e non so cosa ho combinato da allora. Dopo averlo installato non ricordo di aver fatto altro. Adesso vorrei provarlo e testarlo ma non riesco in nessun modo da accedere cambiando la password dell'amministratore.
Ho provato a modificare la password e l'user da db mysql nella tabella degli users ... ma nulla
Any suggestion?

**Comment by giafaweb** [comment]
grazie madbob ... semplicemente non avevo più i dati di accesso (computer andato).
Ho provato a risalire ai dati dalla tabella users del db mysql .... ho decriptato il codice hash ed ho preso nota dell'user dell'amministratore globale ... non ha funzionato ..
allora ho provato ho sostituire i valori sia dell'user che della password criptandola in hash
nulla ... credo che questo abbia lo stesso valore del codice da linea di comando ...
ora vedo nella cartella in cui mi suggerisci di guardares:

**Comment by giafaweb** [comment]
Intanto grazie e scusami se ti importuno ancora. Ho fatto l'installazione un paio di anni fa e la ho parcheggiata senza usarla. Mi piacerebbe farla funzionare e testarne l'uso. In effetti, nella cartella ci sono una serie di file di log (alcuni vuoti)
Il primo con dei dati è del 13 ottobre 2020 e mi restituisce questo avviso:
"[2020-10-13 11:32:13] production.INFO: Scaduto anno sociale GAS Senza Nome "
..... L'ultimo è quello che allego ...... 

[laravel-2021-03-30.log](https://github.com/madbob/GASdottoNG/files/6229367/laravel-2021-03-30.log)

**Comment by madbob** [comment]
Il file /home/pltnet/domains/pas.reteperlaterra.it/public_html/GASdottoNG/code/.env esiste? Ci sono i parametri di accesso al database?
Qual e' lo username dell'utente amministratore?
Hai eseguito `php artisan reset:password username_utente_desiderato nuova_password` per cambiargli la password? Quest'ultimo comando, che output ha dato?
Che valore c'e' nella colonna "password" per l'utente amministratore?

**Comment by giafaweb** [comment]
scusami .. il lavoro ... e grazie ancora ...
1) il file .env è nella localizzazione giusta e mi mi restituisce correttamente i parametri del database con cui ho potuto accedere
2) l'user name per accedere al database è diverso da quello che trovo nel data base come amministratore globale
 - l'user del database è pltnet_gasdotto e ha una sua password
 - l'uer dell'amministratore globale è un'altro .. admin-gasdotto con un'altra password 
 3) ora provo ad eseguire il comando che mi hai indicato  
 4) il valore della colonna password dell'utente amministratore globale è corretto ... una stringa criptata in md5 della password che gli ho attribuito

**Comment by madbob** [comment]
La password *non* è salvata come hash MD5. Non mettere a mano un hash MD5 della password nel database: non funzionerà mai.
Il modo per ottenere un hash valido per la password desiderata è il suddetto comando `php artisan reset:password username password`
