### ISSUE TITLE
informazioni di consegna, movimento: vengono salvate ma non ricaricate dalla scheda di consegna

### ISSUE THREAD

**Issue by orzoweb** [madbob/GASdottoNG#138]
Le informazioni di movimento in **fase di consegna ordine** vengono salvate e compaiono nei movimenti della contabilità, ma se per caso clicco ancora sul bottone consegna nella tab consegne di un ordine, non mi vengono caricare le note data e altri campi precedentemente salvati. In questo modo non si ha la certezza di quali informazioni erano state salvate, ma è necessario spendere tempo e cercarle nell'area contabilità per una verifica o modifica delle stesse. Sarebbe più utile e veloce all'apertura della **modifica movimento** dalla scheda di consegna dell'ordine che venissero caricati i dati dei campi presenti.

![Screenshot 2021-09-17 at 09 53 33](https://user-images.githubusercontent.com/90896628/133748039-9f3a7837-549e-4d44-9caa-3d98427a4e08.png)

**Comment by madbob** [comment]
Cliccando l'icona azzurra accanto alle informazioni di pagamento già si possono consultare tutte le informazioni relative al pagamento stesso di quello specifico ordine.

Riproporre in quel modale le informazioni sull'eventuale pagamento precedente risulta un tantino complesso, soprattutto a causa degli ordini aggregati: in quella fase viene proposto un unico pagamento, complessivo per l'intera consegna, ma dietro le quinte quel pagamento viene eventualmente diviso in molteplici movimenti contabili (uno per ciascun ordine) che a loro volta possono essere individualmente modificati (ad esempio aggiungendo una nota ad uno solo di questi), rendendo impossibile risalire al movimento unico (e fittizio) iniziale.

![Screenshot-20210919183115-1612x487](https://user-images.githubusercontent.com/166089/133935362-789d340c-2257-42ef-b56c-bc7ab4158dc0.png)
