### ISSUE TITLE
Generale: sicurezza

### ISSUE THREAD

**Issue by pcdevoti** [madbob/GASdottoNG#14]
Un socio "molto informatico" e molto bravo mi chiede se abbiamo mai pensato di passare ad https per evitare di mandare in giro password in chiaro.

**Comment by madbob** [comment]
A gennaio Let's Encrypt, che distribuisce certificati SSL gratuiti, [dovrebbe iniziare ad erogare anche quelli per domini wildcard](https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html).
Aspetto quello per registrare un certificato per *.gasdotto.net cosi' non ci penso piu'.

**Comment by madbob** [comment]
Installato certificato wildcard sul dominio *.gasdotto.net
Al momento non è acceduto di default, dunque è possibile accedere alle istanze sia da http://nomeistanza.gasdotto.net/ che da https://nomeistanza.gasdotto.net/, in futuro eventualmente l'uso della connessione HTTPS sarà forzato.
