### ISSUE TITLE
modificatori applicati sul peso della prenotazione / dell'ordine

### ISSUE THREAD

**Issue by madbob** [madbob/GASdottoNG#148]
Aggiungere la possibilità di aggiungere un valore dinamico calcolato in funzione del peso di una prenotazione o di un ordine.
Cfr. https://groups.google.com/g/gasdotto-dev/c/bJURmSbgBrs

**Comment by orzoweb** [comment]
Nel nostro caso, dovendo calcolare un costo di spedizione dato dal peso totale delle merce al Kg, come spesso accade, si potrebbe aggiungere un’operazione di ‘Moltiplica’ che vada a moltiplicare per Kg. e distribuisca poi in base al peso, come da esempio fittizio che segue:

![Screenshot 2021-10-15 at 15 17 52](https://user-images.githubusercontent.com/90896628/137622156-f5212d7f-b059-4be8-818c-86fc97b63858.png)
