### ISSUE TITLE
Indirizzo di spedizione della merce per gli ordini in arrivo

### ISSUE THREAD

**Issue by orzoweb** [madbob/GASdottoNG#149]
Attualmente in GASdotto è possibile indicare un luogo di consegna per l'ordine, che è il luogo di distribuzione o consegna della merce ai gasisti.

Sarebbe utile avere un'altra informazione di default da poter riportare nel riepilogo al fornitore in fase di ordine, è  **l' indirizzo di spedizione** al quale far spedire la merce. Valutare se pensare ad una informazione di base relativa all'indirizzo di spedizione, un dato di default, a livello globale nelle impostazioni del GAS, che possa essere proposto nella scheda ordine e modificato, se necessario, per ogni ordine.

Casi d'uso:

- più sedi dove arriva la merce, differenti da dove viene distribuita o consegnata ai gasisti;
- esigenza di registrare in gasdotto e avere nel riepilogo ordine uno indirizzo di spedizione da ricordare al fornitore;
- quello specifico ordine deve essere spedito ad un altro indirizzo, diverso da quello di default, della sede, ad esempio a quello del referente;
- quello specifico ordine deve essere spedito presso la sede di un altro GAS amico con il quale si è gestita la raccolta ordini, ma non con la funzionalità MULTI-GAS;
- attualmente l'indirizzo di spedizione viene di fatto ripetuto per ogni ordine, ogni volta, via email o al telefono, averlo nel riepilogo generale dell'ordine in PDF, aiuterebbe nel flusso delle informazioni GAS<->Fornitore

**Comment by madbob** [comment]
Una buona parte dei casi che citi sono gia' gestibili con i Luoghi di Consegna
https://www.gasdotto.net/docs/workflow#shippingplaces

- ne possono essere definiti un numero arbitrario
- ogni utente puo' specificare il suo luogo preferito
- le prenotazioni di ogni ordine sono esportabili suddivise per ciascun luogo
- ogni ordine puo' essere abilitato solo per un sotto-insieme di luoghi anziche' tutti
- ogni luogo puo' avere i suoi propri modificatori (e.g. se ci sono spese addizionali)

**Comment by madbob** [comment]
Come scritto sopra: una buona parte dei casi citati sono gia' gestibili con i Luoghi di Consegna.

Per tutto il resto: non credo di strutturare in GASdotto ulteriori campi, dettagli e complicazioni per veicolare informazioni che raramente servono e quando servono possono essere gestite con qualche mail fuori dalla piattaforma.
