### ISSUE TITLE
Sembra che manca l'estensione zip per php

### ISSUE THREAD

**Issue by Pixel-Tux** [madbob/GASdottoNG#162]
Ho provato a costruire un container Docker e mi sono ritrovato con questo errore
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/dusk[v6.15.0, ..., v6.24.0] require ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
    - Root composer.json requires laravel/dusk ^6.15 -> satisfiable by laravel/dusk[v6.15.0, ..., v6.24.0].
```
Sono riuscito a completare la creazione del container aggiungendo nel Dockerfile libzip-dev e assicurandomi che venisse installato per primo.
```dockerfile
FROM php:7

# Install zip
RUN apt-get update && \
    apt-get install -y \
    libzip-dev \
    zip \
    && docker-php-ext-install zip

RUN apt-get install -y unzip && \
    apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev
...
```

**Comment by madbob** [comment]
Confesso di non aver mai usato [il Dockerfile aggiunto tempo fa al repository](https://github.com/madbob/GASdottoNG/blob/master/code/_docker/Dockerfile), anzi stavo valutando di rimuoverlo del tutto appunto perche' non verificato.
Mi apri una pull request con questa correzione?
Grazie :-)
