### ISSUE TITLE
Ordini: come gestire ordini con data di Apertura in futuro

### ISSUE THREAD

**Issue by pcdevoti** [madbob/GASdottoNG#168]

**Comment by pcdevoti** [comment]
PC: non ho capito cosa hai fatto. Se la data di apertura è nel futuro l'ordine viene comunque creato con stato "Prenotazioni aperte". E' voluto? Per capire se poi apre l'ordine devo aspettare domani.

**Comment by madbob** [comment]
Se metti lo stato "Prenotazioni Aperte", resta "Prenotazioni Aperte".
Se metti lo stato "In Sospeso", alla data dell'apertura lo cambia in "Prenotazioni Aperte".
Ho aggiunto una nota nell'help in linea di "Data Apertura Prenotazioni".
