### ISSUE TITLE
Gestione fatture

### ISSUE THREAD

**Issue by pcdevoti** [madbob/GASdottoNG#17]
DB **: Aggiungere numero e data fattura alla tabella ordini (link alla tabella fatture)
DB **: Creare Tabella fatture con link agli ordini
- fornitore
- numero fattura
- data fattura
- stato della fattura (da verificare, verificata, pagata)
- totale imponibile
- totale iva
- totale incassato
- data pagamento
- importo pagato

Implementare controllo fatture

**Comment by madbob** [comment]
Mergiato in master.
