### ISSUE TITLE
rettifica consegne su prezzi modificati

### ISSUE THREAD

**Issue by madbob** [madbob/GASdottoNG#179]
Se le consegne vengono effettuate su prezzi errati dei prodotti, anche se questi vengono corretti dal pannello del fornitore i totali risultano comunque sbagliati (ovviamente e giustamente, avendo gia' generato i relativi movimenti contabili).
In presenza di consegne che coinvolgono prodotti la cui data di ultima modifica e' piu' recente della data di consegna stessa, proporre di ricalcolare i totali sui prezzi attuali dei prodotti e riformulare i movimenti contabili (solo sugli ordini con stato "Prenotazioni Chiuse", quelli in stato "Consegnato" sono consegnati e restano cosi').

**Comment by pcdevoti** [comment]
Francamente mi sembra una richiesta poco giustificata. Se il referente cambia i prezzi dei prodotti a consegne inziate mi sembra ovvio che le consegne debbano essere ripassate per aggiornare i movimenti contabili.

**Comment by madbob** [comment]
Abbiamo gia' visto che l'ovvio non e' sempre cosi' ovvio. E ancora meno ovvio lo e' quando ci sono piu' referenti che mettono mano: questa issue l'ho aperta proprio dopo un caso empirico di consegne nello stesso ordine che sono state effettuate in momenti diversi, con nel mezzo un cambio dei prezzi, cosa che ha fatto saltare tutti i conti e generato non poca confusione.

In caso di situazioni potenzialmente anomale, ma intercettabili e gestibili in modo piu' o meno automatico, meglio aggiungere un alert esplicito che confidare nella capacita' di astrazione dell'utente...
