### ISSUE TITLE
statistiche su prenotazioni (non solo su consegne)

### ISSUE THREAD

**Issue by madbob** [madbob/GASdottoNG#187]
Nel pannello delle statistiche, aggiungere un flag che permetta di mostrare i valori calcolati sul prenotato e non solo sul consegnato.

**Comment by pcdevoti** [comment]
C'è qualcosa che non mi torna: selezionando "Tutto" mi aspetterei di trovare dei dati più alti del solo "Consegnato" invece succede il contrario. Non è che selezionando Tutto prende solo il prenotato?
