### ISSUE TITLE
Gestione prenotazioni di polli interi con peso variabile e anticipo fisso a pollo, consegnati dal fornitore al referente e dal referente ai soci

### ISSUE THREAD

**Issue by 0Lukee** [madbob/GASdottoNG#200]
Salve, avrei necessità di gestire con Gasdotto quanto segue, che ora gestiamo a mano. Tutti i pagamenti in contanti.
 
 
I soci possono **prenotare dei polli interi**, il **costo è tot euro/kg** e **ciascun pollo avrà un proprio peso variabile, determinato solo al momento della consegna**.

I polli ordinati vengono **forniti tutti insieme al referente del GAS che paga il totale** indicatogli sul momento dal fornitore.

Poi **il referente consegna a ciascun socio i suoi polli ordinati e se li fa pagare**.

Per non obbligare il referente ad anticipare la spesa totale al fornitore, il GAS ha convenuto che prima della consegna **i soci versino al referente un anticipo fisso a pollo** (che quindi va moltiplicato per il numero di polli che ha ordinato).
Quindi al momento della consegna il socio riceverà il numero di polli che ha ordinato (ciascuno con scritto il proprio peso) e dovrà saldare al referente solamente la differenza.
 
 
**Esempio concreto:**

**a)** Il fornitore che vende polli interi ha stabilito il costo in 7€/kg

**b)** (Facendo una media dei pesi al ribasso) nel GAS viene stabilito un anticipo a pollo di 15€

**c)** Mario ordina 2 polli e perciò versa 30€ `(15€ x 2 polli)` al referente.
   Giovanni ordina 1 pollo e perciò versa 15€ al referente.

**d)** Il referente si fa consegnare 3 polli dal fornitore e paga il totale indicatogli sul momento, 62,30€: usa 45€ ricevuti in anticipo dai soci e mette di tasca sua la differenza di 17,30€ `(62,30€ - 45€)`.

**e)** Mario si reca dal referente per ritirare i 2 polli che aveva ordinato, c'è scritto che pesano rispettivamente 3,1kg e 2,8kg: quindi costano 21,70€ `(3,1kg x 7€/kg)` e 19,60€ `(2,8kg x 7€/kg)`, totale 41,30€. Avendo già anticipato 30€, Mario dovrà saldare al referente solo 11,30€ `(41,30€ - 30€)`.
   Giovanni si reca dal referente per ritirare 1 pollo che aveva ordinato, c'è scritto che pesa 3kg: quindi costa 21€ `(3kg x 7€/kg)`. Avendo già anticipato 15€, Giovanni dovrà saldare solo 6€ `(21€ - 15€)`.
 
 
Ho provato in tutti modi, con combinazioni di opzioni, moltiplicatori e altro, ma non sono riuscito a gestirlo.
Grazie.

P.s. Potrebbe verificarsi la stessa necessità con prenotazioni di forme intere di formaggio artigianali che abbiano un range di peso variabile.

**Comment by pcdevoti** [comment]
Ciao, credo di poterti aiutare ma in questo momento sono in vacanza.
Possiamo rimandare a fine settimana e magari sentirci a voce+video?
Saluti,
Pier Carlo
Ps: puoi rispondermi su ***@***.*** e/o contattarmi al 340
338 2641


Il Mar 11 Apr 2023, 01:22 0Lukee ***@***.***> ha scritto:

**Comment by madbob** [comment]
La questione del pagamento a peso è facilmente gestibile. Nel tuo caso specifico, dato il prodotto "Pollo" definisci come Prezzo Unitario 7€ - inteso come prezzo al chilo - e come Pezzatura il peso medio del singolo pollo, ad esempio 3 per intendere 3kg. Dati questi parametri, le prenotazioni avvengono per unità (1 pollo, 2 polli, 3 polli... Ciascuno del costo di 7€ * 3 = 21€) e all'atto della consegna verrà chiesto il peso effettivamente consegnato e sarà conseguentemente calcolato il costo.

Altro discorso è il pagamento anticipato. È possibile definire un modificatore con "Operazione = Passivo" per farsi calcolare un anticipo, e dunque avere la somma di tutti gli anticipi complessivi, ma non c'è un modo semplice per fare parte del pagamento prima e parte dopo.

L'unica soluzione che mi viene in mente è
- definire un modificatore sul prodotto Pollo come detto sopra: Passivo, con valore assoluto di 15€
- raccogliere le prenotazioni, e farsi calcolare gli anticipi dovuti da ciascuno
- raccogliere i soldi
- prima della consegna, modificare il modificatore precedentemente impostato per comportarsi come Operazione = Sottrazione (lasciando il valore assoluto di 15€)

In questo modo, all'atto della consegna della singola prenotazione, impostando il peso reale (ad esempio: 3.1kg) verrà effettuato il calcolo:
7€ (prezzo unitario, al kg, precedentemente definito) * 3.1 (chili effettivamente consegnati) - 15€ (applicato dal modificatore, perché precedentemente pagati) = 6.70€ da pagare.

Questa soluzione non è però consigliata se fai affidamento sulla contabilità interna di GASdotto, e ancor peggio se intendi effettuare poi la verifica delle fatture: con questo sistema sul saldo del fornitore ci finiscono solo i soldi pagati a posteriori, non gli anticipi, dunque poi non ti torna nessun conto...

**Comment by pcdevoti** [comment]
Mai chiedere a un softwarista come usare il software che ha sviluppato.
Secondo me c'è una soluzione molto più semplice ma un po lunga da spiegare
via telefono.
Se mi date tempo di rientrare dall'Olanda giovedì, ne parliamo.
Ciao,
Pier Carlo

Il Mar 11 Apr 2023, 17:06 Roberto Guido ***@***.***> ha
scritto:

**Comment by pcdevoti** [comment]
Ciao,

io sono tornato e sono disponibile per parlarti del vostro problema. Ho visto che il mio inridizzo mail privato è stato censurato nella mia precedente risposta per cui cerco di mandartelo in modo “furbetto” piercarlo.devoti @ gmail.com

 

Fammi sapere se e come possiamo riprendere il discorso.

 

Buona serata,

Pier Carlo

 

From: 0Lukee ***@***.***> 
Sent: Tuesday, April 11, 2023 1:22 AM
To: madbob/GASdottoNG ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [madbob/GASdottoNG] Gestione prenotazioni di polli interi con peso variabile e anticipo fisso a pollo, consegnati dal fornitore al referente e dal referente ai soci (Issue #200)

 

Salve, avrei necessità di gestire con Gasdotto quanto segue, che ora gestiamo a mano. Tutti i pagamenti in contanti.
 
 
I soci possono prenotare dei polli interi, il costo è tot euro/kg e ciascun pollo avrà un proprio peso variabile, determinato solo al momento della consegna.

I polli ordinati vengono forniti tutti insieme al referente del GAS che paga il totale indicatogli sul momento dal fornitore.

Poi il referente consegna a ciascun socio i suoi polli ordinati e se li fa pagare.

Per non obbligare il referente ad anticipare la spesa totale al fornitore, il GAS ha convenuto che prima della consegna i soci versino al referente un anticipo fisso a pollo (che quindi va moltiplicato per il numero di polli che ha ordinato).
Quindi al momento della consegna il socio riceverà il numero di polli che ha ordinato (ciascuno con scritto il proprio peso) e dovrà saldare al referente solamente la differenza.
 
 
Esempio concreto:

a) Il fornitore che vende polli interi ha stabilito il costo in 7€/kg

b) (Facendo una media dei pesi al ribasso) nel GAS viene stabilito un anticipo a pollo di 15€

c) Mario ordina 2 polli e perciò versa 30€ (15€ x 2 polli) al referente.
   Giovanni ordina 1 pollo e perciò versa 15€ al referente.

d) Il referente si fa consegnare 3 polli dal fornitore e paga il totale indicatogli sul momento, 62,30€: usa 45€ ricevuti in anticipo dai soci e mette di tasca sua la differenza di 17,30€ (62,30€ - 45€).

e) Mario si reca dal referente per ritirare i 2 polli che aveva ordinato, c'è scritto che pesano rispettivamente 3,1kg e 2,8kg: quindi costano 21,70€ (3,1kg x 7€/kg) e 19,60€ (2,8kg x 7€/kg), totale 41,30€. Avendo già anticipato 30€, Mario dovrà saldare al referente solo 11,30€ (41,30€ - 30€).
   Giovanni si reca dal referente per ritirare 1 pollo che aveva ordinato, c'è scritto che pesa 3kg: quindi costa 21€ (3kg x 7€/kg). Avendo già anticipato 15€, Giovanni dovrà saldare solo 6€ (21€ - 15€).
 
 
Ho provato in tutti modi, con combinazioni di opzioni, moltiplicatori e altro, ma non sono riuscito a gestirlo.
Grazie.

P.s. Potrebbe verificarsi la stessa necessità con prenotazioni di forme intere di formaggio artigianali che abbiano un range di peso variabile.
