### ISSUE TITLE
Ordini/Prodotti: da cell non si può aprire la scheda prodotto

### ISSUE THREAD

**Issue by pcdevoti** [madbob/GASdottoNG#204]
Magari può essere l'occasione per rivedere cosa si può o non si può fare/vedere da cell

**Comment by madbob** [comment]
Sugli schermi piccoli nascondo volutamente quella icona, per non affollare troppo la già troppo affollata tabella.
Eventualmente si può fare che il nome del prodotto diventa cliccabile e si comporta come l'icona (= apre il modale di dettaglio).

**Comment by pcdevoti** [comment]
In realtà sono parecchie le cose che da cell sono precluse. Magari ne parliamo una sera così vediamo cosa può avere senso visto che sembra che ormai siano tantissimi gli utenti che accedono a GASdotto prevalentemente dal telefono

**Comment by pcdevoti** [comment]
Non ho capito se poi hai fatto qualcosa (ma su gasnottong mi sembra non sia cambiato nulla) o se ne dobbiamo parlare

**Comment by madbob** [comment]
Si, e' cambiato qualcosa, ho provato adesso: usando lo smarphone, aprendo il pannello delle prenotazioni e cliccando sul nome del prodotto (che e' blu, ad evidenziare il fatto che e' un link cliccabile), si apre il modale con i dettagli.

**Comment by pcdevoti** [comment]
L'issue però riguarda anche gli ordini, non solo le prenotazioni ...
