### ISSUE TITLE
Ordini aggregati: quando la data di chiusura prenotazioni non è la stessa per tutti gli ordini non tiene conto della data di chiusura prenotazioni dei singoli ordini, in fase di inserimento/variazione delle prenotazioni

### ISSUE THREAD

**Issue by pcdevoti** [madbob/GASdottoNG#205]

**Comment by pcdevoti** [comment]
Direi che ci siamo. Unico piccolo problema: come totale generale della prenotazione viene ripostato solo il totale delle prenotazioni aperte anzichè il totale di TUTTE le prenotazioni

**Comment by madbob** [comment]
Non ho capito in quale circostanza ti mostra il totale solo delle prenotazioni aperte.

Ho appena provato sul pannello della prenotazione di un ordine aggregato, con un ordine chiuso ed uno aperto, e mi mostra il totale complessivo di tutto.
