### ISSUE TITLE
Integrare Laravel Sail

### ISSUE THREAD

**Issue by PixelTux** [madbob/GASdottoNG#208]
Ho notato che Docker è stato rimosso, e ha senso considerando che ora è richiesto `PHP >= 8.1`. Di conseguenza, tutto il resto doveva essere aggiornato. Tuttavia, poiché stiamo utilizzando `Laravel >= 8`, mi piacerebbe integrare `Laravel Sail`, che, a differenza della vecchia configurazione, richiede una manutenzione minima o addirittura nulla. Cosa ne pensi? Ha senso dedicare un po' di tempo per e vedere cosa si può fare?

**Comment by PixelTux** [comment]
Sono riuscito ad implementare Sail molto facilmente, ma ho riscontrato alcuni problemi con Sass.
Uno dei problemi che ho incontrato era il seguente:
```
SassError: Variabile non definita.
   ╷
55 │     "primary": $primary-text-emphasis-dark,
   │                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
```
Ho risolto questo problema impostando `variables-dark` nel file `resource/assets/sass/gasdotto.scss`.
L'altro problema è il seguente:
```
SassError: $color2: var(--bs-border-color) non è un colore valido.
    ╷
212 │   @return mix(black, $color, $weight);
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
```
Questo errore è causato da
`@import '~select2-bootstrap-5-theme/src/include-all`, nello specifico nel file:
```
node_modules/select2-bootstrap-5-theme/src/_variables.scss
```
alla riga:
```
78 $s2bs5-clear-icon: str-replace($btn-close-bg, #{$btn-close-color}, #{shade-color($s2bs5-border-color, 50%)}) !default;
```
Per scopi di test, ho cambiato` #{shade-color` in `#{transparent` e funziona correttamente. Tuttavia, non ho dedicato molto tempo a capire cosa fa effettivamente shade-color. Ho notato che il pacchetto `select2-bootstrap-5-theme` sembra essere inattivo da circa un anno.
Inoltre:
```
public/mix-manifest.json
public/js/gasdotto.js
public/css/gasdotto.css
public/fonts/vendor/bootstrap-icons/bootstrap-icons.woff
public/fonts/vendor/bootstrap-icons/bootstrap-icons.woff2
```
Mi chiedevo se i file generati da Sass dovrebbero essere aggiunti alla lista di `.gitignore`, in quanto vengono rigenerati ogni volta durante lo sviluppo quando si utilizza il comando `npm run development`?

Un'ultima cosa, ho scritto le istruzioni per installare Sail nel file README.md in inglese e mi sono dimenticato di tradurle in italiano. Spero che non sia un problema.
Puoi trovare tutto questo qui:
https://github.com/PixelTux/GASdottoNG/tree/sail

**Comment by madbob** [comment]
Molto bene per Laravel Sail!

Per gli errori in fase di compilazione degli assets: ho eseguito `npm update` sulla mia istanza locale ed effettivamente mi riporta gli stessi errori, a prima vista potrebbe dipendere dal fatto che Bootstrap 5.3 (rilasciato poche settimane fa) ha cambiato i nomi di qualche variabile Sass. Forse una soluzione e' forzare in `package.json` l'utilizzo della versione 5.2, in attesa che vengano adeguate anche le dipendenze (tra cui il tema Bootstrap di [select2](https://select2.org/)).

**Comment by madbob** [comment]
Essendo io pigro spesso tengo gli assets compilati direttamente nel repository, cosi' non li devo ricompilare in fase di deploy, ma in effetti se piu' persone smanettano sullo stesso repository e' ragionevole escluderli. Semmai metti un file `.gitignore` uguale a [questo](https://github.com/madbob/GASdottoNG/blob/master/code/storage/logs/.gitignore) in `public/js`, `public/css` e `public/fonts`.

Il README lo preferirei in italiano, considerando il pubblico principale di GASdotto ;-)
