### ISSUE TITLE
Profilo utente/Contabilità: selezionando il periodo di ricerca il sistema si blocca

### ISSUE THREAD

**Issue by pcdevoti** [madbob/GASdottoNG#210]
Il debug mi segnala un 403
GET http://gasdottong.madbob.org/movements?startdate=Lunedì 01 Maggio 2023&enddate=Lunedì 12 Giugno  023&generic_target_id=francalanci&generic_target_type=App\User&_=1686554687898 [HTTP/1.1 403 Forbidden 1813ms]

**Comment by madbob** [comment]
Fixed in cdef929d2a447ef29d14adb437a0b23289602b21
