### ISSUE TITLE
prenotazioni: aggiungere filtro globale per le categorie

### ISSUE THREAD

**Issue by madbob** [madbob/GASdottoNG#211]
In caso di ordini aggregati, nel pannello delle prenotazioni ogni fornitore ha il suo blocco individualmente filtrabile per categoria di prodotto. Sarebbe utile un filtro "globale" che operi sull'intero contenuto dell'ordine aggregato, e che sia visibile anche su mobile (attualmente e' nascosto).

**Comment by pcdevoti** [comment]
Non c'è modo di annullare la selezione della categoria per tronare all'elenco completo

**Comment by madbob** [comment]
Cliccando su quella attualmente selezionata, viene deselezionata e pertanto torna allo stato originale (nessuna selezione = mostra tutte le categorie). E' sempre stato cosi', benche' effettivamente poco intuitivo.
