### ISSUE TITLE
Resettare modale creazione ordine dopo che ne e' stato creato uno.

### ISSUE THREAD

**Issue by PixelTux** [madbob/GASdottoNG#212]
[TODO link reference](https://github.com/users/madbob/projects/1/views/1?pane=issue&itemId=9821635)
Non riesco a riprodurre il problema. Attualmente, quando creo un ordine, il modale viene resettato, l'unica differenza che ho notato è che i valori predefiniti sono `Mai` invece della data odierna (come mostrato nello screenshot).

**Prima**
![Screenshot 1](https://i.ibb.co/pz5YdhK/Screenshot-from-2023-06-16-15-48-39.png")
**Dopo**
![Screenshot 2](https://i.ibb.co/89kHRc8/Screenshot-from-2023-06-16-15-49-08.png")

Sto sbagliando per caso qualcosa o e' probabile che questo non si verifica piu?

**Comment by madbob** [comment]
Il problema e' essenzialmente quello (non vengono aggiornate le date) e in piu' non viene azzerato il blocco con le date future del fornitore selezionato (che si trova [qui](https://github.com/madbob/GASdottoNG/blob/master/code/resources/views/order/base-edit.blade.php#L38): se creo un ordine per un fornitore che ha delle date salvate sul calendario, e riapro il modale, mi ritrovo ancora quelle stesse date anche se il fornitore selezionato e' un altro).

Forse il metodo piu' rapido per sistemare questa cosa e' non gestire quel modale di creazione come tutti gli altri (ovvero: delegandolo a `commons.addingbutton`, che adotta sempre lo stesso comportamento per tutti) ma usare un modale nuovo e pulito caricato daccapo tutte le volte usando il sistema degli `async-modal` (come ad esempio [questo](https://github.com/madbob/GASdottoNG/blob/master/code/resources/views/pages/orders.blade.php#L26), che ogni volta che viene cliccato effettua una chiamata Ajax verso [questo controller](https://github.com/madbob/GASdottoNG/blob/master/code/app/Http/Controllers/DatesController.php#L26)).
