### ISSUE TITLE
Ordini/Luoghi di consegna: il luogo di consegna con compare nel "Dettaglio consegne" e non viene correttamente gestito nel "Riassunto prodotti"

### ISSUE THREAD

**Issue by pcdevoti** [madbob/GASdottoNG#215]

**Comment by pcdevoti** [comment]
Dettaglio consegne: l'ordinamento è corretto ma non è evidenziata l'indicazione dei luoghi di consegna
Riassunto prodotti: non tiene conto dei luoghi di consegna

**Comment by pcdevoti** [comment]
Ho visto che hai chiuso l'issue, ma è pubblicato su gasdottong? Ho appena provato e mi sembra non sia cambiato nulla

**Comment by pcdevoti** [comment]
Ok per il dettaglio consegne. Invece la soluzione adottata per il riepilogo mi convince poco. Mi sarei aspettato una soluzione come quella del Dettaglio con l'elenco "spezzato" in sezioni separate con una testata ad indicare il luogo di consegna

**Comment by madbob** [comment]
Ho dovuto rivedere un po' massicciamente il codice per la formattazione di questi documenti, per aggiungere le corrette indicazioni sui luoghi di consegna.

**Comment by pcdevoti** [comment]
Perfetto. Ma perchè nel Riepilogo è sparita l'intestazione iniziale?

**Comment by pcdevoti** [comment]
Richiedendo il Riassunto prodotti ordinato per Luogo di consegna non genera nulla, scompare tutto dalla pagina e mi da errore GET
[http://gasdottong.madbob.org/orders/document/azienda-agri-bio-d-apolito::01-agosto-2023/summary?shipping_place=all_by_place&fields[]=name&fields[]=quantity&fields[]=measure&fields[]=price&status=booked&format=pdf&recipient_mail_value[]=agribiodapolito@gmail.com&recipient_mail_value[]=francar360@gmail.com&recipient_mail_value[]=sonnessa.maria@virgilio.it&recipient_mail_value[]=&subject_mail=Documento+allegato&body_mail=](http://gasdottong.madbob.org/orders/document/azienda-agri-bio-d-apolito::01-agosto-2023/summary?shipping_place=all_by_place&fields%5B%5D=name&fields%5B%5D=quantity&fields%5B%5D=measure&fields%5B%5D=price&status=booked&format=pdf&recipient_mail_value%5B%5D=agribiodapolito%40gmail.com&recipient_mail_value%5B%5D=francar360%40gmail.com&recipient_mail_value%5B%5D=sonnessa.maria%40virgilio.it&recipient_mail_value%5B%5D=&subject_mail=Documento+allegato&body_mail=)
[HTTP/1.1 500 Internal Server Error 2018ms]
