### ISSUE TITLE
tracciamento modifiche

### ISSUE THREAD

**Issue by madbob** [madbob/GASdottoNG#231]
Oltre alla data di ultima modifica - gestita nativamente da Laravel - sarebbe opportuno tenere traccia anche dell'utente che compie la modifica, e mostrare - magari vicino al pulsante di salvataggio - chi e quando ha fatto l'ultima modifica.
Questo è utile per identificare attività da parte degli utenti, e meglio isolare i comportamenti anomali del software rispetto agli interventi anomali manuali.
Da applicare a utenti, prodotti, fornitori, ordini, prenotazioni, modificatori, luoghi di consegna, movimenti contabili.

**Comment by pcdevoti** [comment]
Ho fatto questa prova: ho aggiunto un prodotto ad una Prenotazione e ho notato che:
1 - in booked_products non è previsto di tenere traccia di chi ha fatto la modifica
2 - la modifica non viene segnalata neppure a livello di bookings
Non so se questo comportamento è voluto ma la Prenotazioni sono proprio uno di quei casi in cui sarebbe utile tracciare le modifiche
