### ISSUE TITLE
Utenti, Stato Quote: evidenziare quote scadute

### ISSUE THREAD

**Issue by pcdevoti** [madbob/GASdottoNG#233]
Quando registro la nuova quota non resetta la banda rossa finchè non faccio refresh

**Comment by pcdevoti** [comment]
Il problema persiste; finchè non riaggiorno la pagina (e poi devo rientrare il Gestione quote) rimane la banda rossa. Immagino sia solo un problema di aggiornamento della pagina ma la data viene aggiornata, la banda rossa no.

**Comment by madbob** [comment]
Non capisco... Ho provato sia con Chrome che con Firefox, e funziona.
Del resto, se cambia la data, vuol dire che sta effettivamente ricaricando quella porzione di pagina coi dati aggiornati della nuova quota.
Che data stai impostando per il versamento della nuova quota che non torna bianca e resta rossa?

**Comment by pcdevoti** [comment]
La data del giorno, come proposto da GASdotto
