### ISSUE TITLE
Unità di misura continue: problema con campo Peso

### ISSUE THREAD

**Issue by pcdevoti** [madbob/GASdottoNG#237]
se definisco un UM continua, per esempio €, diversa da Chili, non mi permette di editare il campo Peso per i prodotti che la usano e poi utilizza la quantità come peso. In presenza di "arrotondamenti" sulle consegne, questo fatto sballa il calcolo dei modificatori basati sul peso

**Comment by madbob** [comment]
In effetti l'assunzione di base è che le unità continue siano sempre unità di peso. Che è una assunzione sbagliata, ma almeno semplifica qualche comportamento.

Alternative:
- più semplice, ma ripetitiva: non fare nessuna assunzione e far esplicitare sempre il peso. Per quello che è misurato in Chili, bisogna comunque sempre metterci a mano "1"
- più versatile, ma prona a errori: in fase di configurazione delle unità, permettere di specificare un peso di default. E dunque tutto quello che ha "Chili" viene messo a 1 una volta sola, e volendo può essere applicato anche a qualsiasi altra cosa (con pro e contro di avere dei default che magari vengono applicati in modo quasi inconsapevole dall'operatore)
- più macchinosa dal punto di vista dell'usabilità: in fase di configurazione delle unità, aggiungere un ennesimo flag per distinguere cosa rappresenta nativamente un peso e cosa no, e trattarlo di conseguenza (per quel che rappresenta un peso, non chiede un peso per il prodotto)

**Comment by pcdevoti** [comment]
Sarei per la soluzione 1 con una piccola integrazione: quando per un prodotto viene indicata una UM continua, proporre di default Peso=1, visto che nella quasi totalità dei casi si tratterà di chili; se poi non è così il referente cambierà il valore. Forse aggiungerei anche un controllo che segnali un Warning nel caso il valore di Peso sia diverso da 0 e 1 (al momento non riesco ad immaginare casi diversi).
