### ISSUE TITLE
Ordini/Invio messaggio al referente a chiusura prenotazioni

### ISSUE THREAD

**Issue by pcdevoti** [madbob/GASdottoNG#238]
Dovrebbe essere configurabile a livello di Configurazioni, come tutti gli altri messaggi. Invece da un po' viene inviato comunque con allegati i due file di riepilogo

**Comment by pcdevoti** [comment]
Bella soluzione. A questo punto, volendo generalizzare ulteriormente, forse non sarebbe complicato aggiungere anche la selezione dei fornitori a cui applicare le diverse opzioni (p.es. per un ordine settimanale forse non ha molto senso inviare tutte ste notifiche, mentre per un ordine annuale è fondamentale)

**Comment by pcdevoti** [comment]
OK per lo spostamento della configurazione a livello di fornitore ma nelle Configurazioni generali è sparita la possibilità di personalizzare il testo del messaggio da inviare. Rivediamo un attimo il tutto quando ci sentiamo

**Comment by madbob** [comment]
La configurazione della mail "Notifica destinata ai fornitori alla chiusura automatica dell'ordine" viene visualizzata quando c'è almeno un fornitore che ha l'invio automatico attivato, altrimenti è ridondante.

**Comment by pcdevoti** [comment]
Aggiungere opzione per invio di Dettaglio consegne+Riassunto prodotti
