### ISSUE TITLE
Modificatori: se viene definita una soglia a livello di ordine, la stessa solglia viene poi applicata alle singole prenotazioni per decidere se applicare il modificatore alla prenotazione. Vedi ordine Biogold su gasdottong

### ISSUE THREAD

**Issue by pcdevoti** [madbob/GASdottoNG#245]

**Comment by pcdevoti** [comment]
Ho visto che hai chiuso questo item ma su gasdottong mi sembra non sia cambiato nulla.

**Comment by madbob** [comment]
Ho fatto una modifica ma mi sono poi reso conto che spacca il comportamento di altri modificatori, in altre circostanze. Lo devo rivedere un altro po'.
