### ISSUE TITLE
Reset password al primo login

### ISSUE THREAD

**Issue by twproject** [madbob/GASdottoNG#250]
sarebbe utile aggiungere un flag in modo tale da forzare il cambio della password al primo login dell'utente.

**Comment by madbob** [comment]
Nel pannello di amministrazione degli utenti, l'amministratore può cambiare forzatamente la password di qualcuno e già ha il flag "Forza cambio password al prossimo login". In sede di creazione di un nuovo utente (manuale o da CSV) è possibile specificare solo un indirizzo email, ed il nuovo utente riceve un link di invito che al primo login gli chiederà di impostare autonomamente la propria password.
Quali altri contesti ti sembra che non siano coperti?

**Comment by twproject** [comment]
Grazie della risposta, le casistiche previste direi che coprono tutto.
Non trovo però il Forza cambio password nel pannello amministratore

![image](https://github.com/madbob/GASdottoNG/assets/7046065/f28ad53d-2628-4932-ac4a-8ba93e74e886)

**Comment by madbob** [comment]
Cliccando sull'input del campo "Password" si apre il modale che chiede di inserire la nuova password due volte ed il suddetto flag di forzatura.

![screenshot-gasdottong it-2024 01 19-11_21_26](https://github.com/madbob/GASdottoNG/assets/166089/ebcf9f37-4194-4518-a87d-eca59f31e18c)

**Comment by twproject** [comment]
Ok ora l'ho trovato e funziona!!!
Sarebbe utile avere lo stesso flag anche in fase di creazione dell'utente.

Colgo l'occasione per segnalare che nelle indicazioni di import da csv sarebbe interessante avere la lista dei campi obbligatori o un esempio di come costruire il file csv.

Grazie
