### ISSUE TITLE
Esportazione csv e prezzi unitari

### ISSUE THREAD

**Issue by danielezambelli** [madbob/GASdottoNG#253]
Nell'esportazione csv di un ordine, i prezzi unitari hanno i decimali separati dalla virgola e racchiusi tra virgolette, mentre il "Totale prezzo" ha i decimali separati dal punto. Es:

Prezzo unitario: "12,00"
Totale complessivo: 53.50

Quando importo il csv in un foglio di calcolo,  i prezzi unitari vengono considerati delle stringhe,
mentre i totali complessivi vengono considerati numeri.

Questo differente trattamento non mi pare che abbia senso.

Io ho bisogno che anche i prezzi unitari siano trattati come numeri. 
Il fatto di doverli modificare a mano uno per uno, oltre a essere noioso, è prono a errori.

Propongo che in tutti i numeri decimali, la virgola sia sostituita dal punto o, comunque, siano resi come numeri e non come stringhe.

Grazie per l'attenzione, 

  Daniele.

**Comment by danielezambelli** [comment]
Ottimo, grazie.

**Comment by pcdevoti** [comment]
Volendo c'è ancora una discrepanza: per i prezzi usi il "." come separatore decimale mantre per le quantità usi la ","
