### ISSUE TITLE
Dubbio su consuntivi contabilità

### ISSUE THREAD

**Issue by twproject** [madbob/GASdottoNG#254]
Ciao  a tutti,
sto gestendo i primi ordinativi via gasdotto e ho un dubbio sulla parte contabile. 
Per un fornitore ho ordinato 168€ di Arance e arrivata la merce ho segnato il Pagamento al fornitore tramite la funzione apposita nell'ordine
Ho consegnato le varie casse ai colleghi e ricevuto i soldi segnando i relativi pagamenti (Pagamento prenotazione da parte di un socio)
Andando su contabilità e ricercando per fornitore mi trovo tutti i movimenti contabili ma il valore totale mi torna come somma di tutti (336€ composto dai 168 pagati e dai 168 ricevuti) mentre mi aspettavo di avere un totale di 0€
E' tutto corretto o devo sistemare qualche flusso?

![immagine](https://github.com/madbob/GASdottoNG/assets/7046065/471b86aa-527b-4052-95cf-a798d75a638d)

**Comment by pcdevoti** [comment]
Credo sia necessario che verifichiamo la vostra procedura di consegne e chiusura degli ordini per la parte contabile.

Contattami privatamente su ***@***.*** ***@***.***>  o whatsapp al 340 338 2641 e combiniamo una call.

 

Buona domenica,

Pier Carlo

 

From: twproject ***@***.***> 
Sent: Wednesday, January 31, 2024 3:51 PM
To: madbob/GASdottoNG ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [madbob/GASdottoNG] Dubbio su consuntivi contabilità (Issue #254)

 

Ciao a tutti,
sto gestendo i primi ordinativi via gasdotto e ho un dubbio sulla parte contabile.
Per un fornitore ho ordinato 168€ di Arance e arrivata la merce ho segnato il Pagamento al fornitore tramite la funzione apposita nell'ordine
Ho consegnato le varie casse ai colleghi e ricevuto i soldi segnando i relativi pagamenti (Pagamento prenotazione da parte di un socio)
Andando su contabilità e ricercando per fornitore mi trovo tutti i movimenti contabili ma il valore totale mi torna come somma di tutti (336€ composto dai 168 pagati e dai 168 ricevuti) mentre mi aspettavo di avere un totale di 0€
E' tutto corretto o devo sistemare qualche flusso?

immagine.png (view on web) <https://github.com/madbob/GASdottoNG/assets/7046065/471b86aa-527b-4052-95cf-a798d75a638d>

**Comment by madbob** [comment]
Il totale rappresentato al fondo di quella tabella può essere un po' fuorviante, essendo la somma aritmetica dei valori assoluti dei movimenti contemplati; assume un senso se si applica qualche filtro specifico nel pannello di amministrazione, mentre si fa qualche ricerca particolare.

Quello che varia è il saldo del fornitore, che puoi consultare cliccando "Stato Fornitori" in alto nel pannello della Contabilità. Lì dovresti vedere che il saldo di Arance&Co adesso è zero, perché hai incassato 168€ e gli hai pagato 168€.
Il saldo si incrementa quando ricevi i pagamenti delle prenotazioni, e si riduce quando paghi il fornitore. Se è maggiore di zero, devi dargli dei soldi che hai incassato; se è minore di zero, gli hai dato più soldi di quelli che hai incassato; se è a zero, va tutto bene ;-)
