### ISSUE TITLE
ordini automatici per apertura, chiusura o consegna

### ISSUE THREAD

**Issue by madbob** [madbob/GASdottoNG#259]
Attualmente, nel definire la frequenza degli ordini automatici, si può solo definire una ciclicità basata sulla data di apertura. Sarebbe utile permettere di definire questa ciclicità anche sulle date di chiusura o di consegna (e.g. consegna il secondo ed il quarto giovedi del mese) e calcolare conseguentemente le altre date.

Marzia Mariotto, GAS Tortona.

**Comment by pcdevoti** [comment]
Così com'è adesso secondo me è poco chiara la modalità di configurazione. Mi rendo conto che è un casino ma temo dobbiamo ripensarla

**Comment by madbob** [comment]
Aggiungere etichette esplicite "apertura", "chiusura" e "consegna" nel pannello di amministrazione.

**Comment by pcdevoti** [comment]
Non so se è "by design" ma mancano i controlli di congruenza. Per esempio è possibile definire che la consegna avvenga prima della chiusura.

**Comment by pcdevoti** [comment]
Adesso è ok se si parte da apertura o chiusura ma non se si parte da "Consegna": è possibile definire che la chiusura sia prima dell'apertura
