### ISSUE TITLE
Attempt to assignment "target" property on null

### ISSUE THREAD

**Issue by PixelTux** [madbob/GASdottoNG#263]
Oggi ho cercato di aggiornare la mia istanza locale con le nuove modifiche e ho riscontrato questo errore:
![Screenshot from 2024-02-26 00-36-57](https://github.com/madbob/GASdottoNG/assets/66007913/65bcced8-60cf-4bd0-9483-3595dba2256c)
Nel mio caso, il problema è stato causato dal fatto che $this->action era vuoto, quindi $node non veniva assegnato nella fase "switch". Ecco il risultato della stampa di $this->action:
![Screenshot from 2024-02-26 00-39-13](https://github.com/madbob/GASdottoNG/assets/66007913/8fb91aa5-c0a6-474b-970e-232f0711fe6b)
Facendo una verifica su `$this->action` in riga `113`, sono riuscito a far ripartire la piattaforma.
@madbob potresti dare un'occhiata per vedere se questo fix può causare altre complicazioni o se è un intervento sicuro?

L'errore è riproducibile eseguendo una nuova installazione con i seguenti comandi:
```php
php artisan migrate:fresh --seed
php artisan db:seed --class=DemoSeeder 
```

**Comment by PixelTux** [comment]
Visto ora il commit [c2f85a7](https://github.com/madbob/GASdottoNG/commit/c2f85a7f63698856f06329a36281ba4964e699c0), io avevo aggiunto a riga 113
```php
  if ($this->type != 'order' || empty($this->action)) {
            return $ret;
  }
  ```
  Pero vedo che la cosa era molto più complessa :smile:

**Comment by madbob** [comment]
Deriva dal fatto che nel commit b5c1038 (#259) ho modificato un po' di cose nella gestione delle date, aggiungendo e cambiando un po' di parametri.
L'esecuzione del comando `php artisan fix:database` dovrebbe risolvere.

In generale: quando vedi modifiche sul file `code/app/Console/Commands/FixDatabase.php` è perché probabilmente ho fatto qualche modifica allo schema dei dati, e quel comando serve a correggere e rettificare i dati già esistenti a posteriori.

**Comment by PixelTux** [comment]
Ho notato l'ampio lavoro di sviluppo e refactoring che è stato fatto. Riguardo al problema relativo al "_property on null_" (già  risolto con l'`if` all'interno del `for`) , ho implementato la correzione che avevo in mente. Se ritieni che questa modifica ha senso puoi incorporala, in ogni caso possiamo considerare l'issue risolta e chiudere la discussione. :slightly_smiling_face:

**Comment by madbob** [comment]
[Questo if](https://github.com/madbob/GASdottoNG/commit/b13ea9b3c0689988104018ee96b4843f62c304a9#diff-a03fe589054445476ddd4d076ea1182b90a7e2c728da51b03287347b16fa8a2bR155) dovrebbe essere sufficiente, per arginare l'improbabile caso (improbabile, dopo la rettifica dei dati sul DB) in cui si arrivi in quel punto e l'attributo `action` non sia valorizzato.
