### ISSUE TITLE
Semplificazione delle Installazioni Docker

### ISSUE THREAD

**Issue by PixelTux** [madbob/GASdottoNG#269]
Sto pensando di semplificare l'installazioni tramite Docker/Sail eliminando i requisiti di `php (incluse le estensioni necessarie per Laravel)` e `composer`, in modo da poter eseguire tutto utilizzando solo `Docker` e `Docker Compose`. Ho già testato con successo questa configurazione, ma se pensi che abbia senso, sono disposto a dedicare più tempo per condurre ulteriori test e aggiornare la guida di installazione.

**Comment by madbob** [comment]
Non usando personalmente Docker/Sail non saprei dire, ma non mi è chiaro come il tutto possa funzionare eliminando le estensioni PHP e composer... Non sono comunque dipendenze di Sail?

**Comment by PixelTux** [comment]
Io vedo Docker come una sorta di server esterno (completo con PHP e composer) che condivide una cartella sulla mia macchina e ha gli stessi permessi dentro essa. Per creare questo _"server"_, ho bisogno delle sue caratteristiche che sono definite nel file Dockerfile situato in 'GASdottoNG/code/vendor/laravel/sail/runtimes/8.2/'. Il punto è che la cartella `vendor` viene _"generata"_ da composer, quindi quando clono la repository non esiste. Per evitare di dover installare PHP e composer sulla mia macchina locale, potrei semplicemente costruire prima il container e poi utilizzare PHP e composer che vengono installati all'interno. Quindi, quello che stavo pensando era di includere nei commit la cartella **sail** _(vendor/laravel/sail/*)_ per avere accesso al file `Dockerfile` e allo script **sail** _(vendor/bin/sail)_, così da poter utilizzare il comando `sail` invece dei comandi `docker` subito dal inizio. Questi file vengono sovrascritti durante gli aggiornamenti, quindi è facile da mantenere, in quanto vengono aggiornati automaticamente da composer in caso di modifiche. Cosa ne pensi?

**Comment by PixelTux** [comment]
Banalmente descrivere Sail come commandi Docker e Docker-Composer in stille Laravel per Laravel.

**Comment by madbob** [comment]
Mmm... Mi garba veramente poco committare dentro al repository dei contenuti in `vendor`...

Capisco il punto, ed effettivamente è contestabile il fatto che Sail sia installabile solo avendo a priori a disposizione gli strumenti di sviluppo, ma del resto Sail stesso [viene proposto](https://laravel.com/docs/10.x/sail) come uno strumento di sviluppo - non di deploy - dunque evidentemente, nella sua implementazione, non si sono posti il problema di predisporre un Docker auto-definito.

Molto dipende da come intendi il Docker per GASdotto. Se come uno strumento per agevolare lo sviluppo, è ragionevole assumere che PHP e composer siano installati sulla macchina host (se qualcuno vuol partecipare allo sviluppo di GASdotto, almeno quel minimo di strumenti li deve avere). Se come uno strumento per agevolare il deploy e l'installazione autonoma su un proprio server, sarebbe forse meglio lasciar perdere Sail e tornare - come era prima - al Dockerfile (o ad un file per Docker Compose).

**Comment by PixelTux** [comment]
Mi sembra di aver trovato la soluzione nella documentazione Laravel [Installing Composer Dependencies for Existing Applications](https://laravel.com/docs/11.x/sail#installing-composer-dependencies-for-existing-projects).  Proverò a seguire quella procedura e vedere se funziona. Tuttavia, credo che potrebbe essere la soluzione che stavo cercando.

**Comment by PixelTux** [comment]
Provato e funziona, se sei d'accordo proved ad aggiornare README.md, unica modifica necessaria. :slightly_smiling_face:

**Comment by madbob** [comment]
Aggiudicato ;-)
