### ISSUE TITLE
Ordini/Consegne: segnalare a livello di utente eventuali consegne contestuali di ordini non aggregati (permette a chi gestisce le consegne di ricordare all'utente che ha altri prodotti da ritirare lo stesso giorno)

### ISSUE THREAD

**Issue by pcdevoti** [madbob/GASdottoNG#289]

**Comment by pcdevoti** [comment]
Sarebbe opportuno che la segnalazione avvenisse anche nel file Dettaglio consegne. Comunque intanto metterei online la versione attuale con la segnalazione online

**Comment by madbob** [comment]
Nota: un GAS, evidentemente poco avvezzo alle aggregazioni, mi segnala che questa funzione popola il Dettaglio Consegne di numerose righe nel caso di giornate particolarmente trafficate.

Pertanto ho vincolato l'aggiunta delle informazioni sulle altre prenotazioni da ritirare ad un parametro nel gruppo "Dati Utenti", che di default non è attivo ma, come sempre, può essere abilitato come default sotto Configurazioni -> Ordini e Consegne -> Colonne Attive in Dettaglio Consegne
