### ISSUE TITLE
consegne veloci con amici

### ISSUE THREAD

**Issue by madbob** [madbob/GASdottoNG#290]
Nel caso in cui un "amico" faccia una prenotazione, e l'utente primario no, in fase di consegna veloce le quantità consegnate finiscono sia nella prenotazione dell'amico stesso che in quella proxy dell'utente primario. Verificare il momento in cui viene creata la prenotazione proxy ed il suo stato.

**Comment by pcdevoti** [comment]
Non l'ho davvero testato ma lo verifichiamo direttamente su roccafranca alla prima occasione
