### ISSUE TITLE
Modificatori: svincolare la soglia dall'oggetto del modificatore (p.es. sconto a livello di prodotto ma soglia da calcolare sul totale dell'ordine)

### ISSUE THREAD

**Issue by pcdevoti** [madbob/GASdottoNG#295]

**Comment by madbob** [comment]
Modificatore su prodotto: attivare sul prodotto se l'ordine nel suo complesso raggiunge una certa soglia (e.g. sconto del 5% sul prodotto se l'ordine complessivamente raggiunge i X €).
