### ISSUE TITLE
importazione utente, manca stato e credito obligatorio

### ISSUE THREAD

**Issue by alachina** [madbob/GASdottoNG#30]
In importazione da csv, manca il campo stato degli utenti, in questo modo vengono creati attivi utenti in realtà cessati  Inoltre è obbligatorio un campo credito, campo che nelle vecchie versioni non c'era.

**Comment by madbob** [comment]
Aggiunta la colonna relativa allo stato (true/false).
Il credito non è obbligatorio, se non viene specificato resta a 0.
