### ISSUE TITLE
importazione gdxp stato articoli

### ISSUE THREAD

**Issue by alachina** [madbob/GASdottoNG#31]
In importazione da file gdxp di un fornitore, non sembra caricare correttamente gli stati degli articoli (li carica tutti come ordinabile = SI)

**Comment by madbob** [comment]
In effetti quell'attributo non e' mai stato parte di GDXP, l'ho aggiunto adesso (madbob/GDXP@9c0d20c0ce0a989d7593a76a07c43bb19fd0f745) ma ovviamente non e' retrocompatibile con le versioni più vecchie.
