### ISSUE TITLE
Eliminare Forinotori

### ISSUE THREAD

**Issue by danieledalma** [madbob/GASdottoNG#34]
Non riesco ad eliminare fornitori non più operativi, come si deve procedere?
Grazie
Daniele

**Comment by madbob** [comment]
Ho appena provato a cancellare un fornitore sulla mia istanza locale, ma sembra funzionare.
Ti riferisci ad una istanza hostata su gasdotto.net o altrove? Quale comportamento viene riscontrato? La cancellazione sembra andare a buon fine ma il fornitore torna nell'elenco di quelli disponibili, o si verifica proprio un errore in fase di cancellazione?

**Comment by danieledalma** [comment]
RISOLTO
dopo svariati ragionamenti mi sono reso conto che l utente ROOT ( quello che uso per amministrare) non era inserito nei referenti di quel forinotere
grazie
Daniele
