### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by Batarian711** [madbob/GASdottoNG#40]
Hi. I am a graphic designer. I volunteer to design a logo for open source projects. I can design it for you to use it in the readme file. What dou you say?

**Comment by madbob** [comment]
That would be really cool! The current logo - https://www.gasdotto.net/ - looks a bit outdated...
Do you have a portfolio, or some previous experiences with logo design to show?

**Comment by Batarian711** [comment]
I designed a minimalist logo that would better reflect the name of the project. Is there anything you want to add? What do you think?
![gasdottong](https://user-images.githubusercontent.com/41051393/42682287-cfaf78be-8692-11e8-8d74-cae6c7b59c85.jpg)
