### ISSUE TITLE
revisione traduzione inglese

### ISSUE THREAD

**Issue by madbob** [madbob/GASdottoNG#44]
La traduzione inglese è completa ma necessita di una revisione.

**Comment by Marcormio** [comment]
La traduzione di cosa? C'è un iter particolare per aprire una pull request con la revisione?

**Comment by madbob** [comment]
I files rilevanti sono
https://github.com/madbob/GASdottoNG/blob/master/code/resources/lang/i18n/en_EN/LC_MESSAGES/messages.po
https://github.com/madbob/GASdottoNG/blob/master/code/resources/lang/i18n/en_EN/LC_MESSAGES/javascript.po
ed e' consigliato editarli con un tool specifico (e.g. POEdit).

So per certo che alcune stringhe non sono correttamente tradotte, in virtu' del mio inglese maccaronico: sarebbe opportuno rivederle e fare una PR con le correzioni.

Se può essere utile, qui c'e' una istanza demo dell'applicazione per vedere le stringhe nel loro contesto: https://demong.gasdotto.net/

**Comment by pcdevoti** [comment]
Se non è urgentissimo posso fare io una revisione della traduzione ma avrei bisogno di qualche dritta su POEdit (c'è anche sotto windows?)
