### ISSUE TITLE
traduzione italiano/olandese

### ISSUE THREAD

**Issue by madbob** [madbob/GASdottoNG#45]
E' stata chiesta la traduzione in olandese di GASdotto, ma non so da che parte iniziare.

I files rilevanti, con le stringhe originali in italiano, sono
https://github.com/madbob/GASdottoNG/blob/master/code/resources/lang/i18n/nl_NL/LC_MESSAGES/messages.po
https://github.com/madbob/GASdottoNG/blob/master/code/resources/lang/i18n/nl_NL/LC_MESSAGES/javascript.po
ed e' consigliato editarli con un tool specifico (e.g. POEdit).

Se può essere utile, qui c'e' una istanza demo dell'applicazione per vedere le stringhe nel loro contesto: https://demong.gasdotto.net/

**Comment by pcdevoti** [comment]
Mi dispiace ma su questo non so proprio come aiutare; probabilmente la via più sensata è passare dalla versione inglese, comunque provo a sentire se qualche gasista conosce l'olandese.

**Comment by madbob** [comment]
Sviluppi in corso su https://hosted.weblate.org/projects/gasdottong/translations/nl/
