### ISSUE TITLE
calendario ordini in iCal

### ISSUE THREAD

**Issue by madbob** [madbob/GASdottoNG#47]
Attualmente l'elenco degli ordini e' gia' esposto in RSS, sarebbe utile fare altrettanto in formato iCal.

1) aggiungere icona in dashboard, vicino a quella dell'RSS
2) predisporre una route in GET ed una funzione in OrdersController per generare l'iCal di tutti gli ordini non archiviati
3) bonus: predisporre la funzione per accettare un parametro di filtro per ottenere gli ordini di determinati fornitori (e.g. supplier=fornitore1,fornitore2,fornitore5)

**Comment by pcdevoti** [comment]
Per l'anno in corso inserirei anche gli ordini archiviati
