### ISSUE TITLE
some questions about gasdotto

### ISSUE THREAD

**Issue by jen-do** [madbob/GASdottoNG#59]
Hello,

we would like to use the GASdotto system for a direct import of products from Sicily to Berlin.
I already wrote in an email that we‘ve got  a few questions about some details of the system.

Is it possible 
- ...also to export the 'delivery details' as csv-file (not only as pdf)?
- ...to edit the text of the emails the system is sending automatically, e.g. when a new user registers, the welcome message or the email that is sent to everyone who participated in an order, and add additional information to it?
- We would like the users to register in the system. Is it possible to turn the telephone number in the registration form into an optional field (right now it‘s mandatory for registration to fill that in). 
- And I alread mentioned this in an previous email: The 'Registrati'-button is not visible when visiting the login-screen from a smaller device (like tablet, laptop). It's seems to be covered by the footerline "Powered by GASdotto" and it's also not possible to scoll down in order zu display it. Is there a way to fix that? 

Thanks a lot.
Best regards from Berlin
jenny

**Comment by madbob** [comment]
* the "Deliveries Details" document is a non-tabular document with essential informations intended to be printed to support delivery operations. What about the already existing "Reserved Products Resume" CSV document?
* custom email texts: not yet
* customizable fields in registration form: added just now
* I've introduced a fix a few weeks ago: is it still overlapping?

**Comment by jen-do** [comment]
Thanks for answering so quickly and for already adding features.
It's cool that we can now customize the registration form!!

- I testet the registrati button, but it's still hidden behind the Powered-by-GASdotto overlay on smaller screens and I'm not able to scoll down to actually see the button. (This only concerns a screen width between 980 and 1300px, the height of my viewport is about 700px). Of cause, it's also depending on how much content you to display on the login screen (when we leave it out this might save some space).

- There is another issue with smaller viewports: when I'm logged in as an admin some of the buttons displayed at the top of the main-content (like 'add new user', 'create new order') are not visible, because the main nav (that's increasing in it's height on smaller screens) is overlapping. Is it possible to switch to a drop-down hamburger style menu also for screen width above 780px?

- regarding the "Delivery Details": this is not such an important point. The document already gives us a good overview over all information we need for distríbuting the delivered goods among the persons who order. We thought of adding some formatting to it to, because the amount of articles ordered and the measure unit are displayed quite close to another without a column line inbetween. 

All the best,
jenny

**Comment by pcdevoti** [comment]
Ma questo non si potrebbe chiudere?

**Comment by jen-do** [comment]
sì, certo. sorry, lo dimenticato.
