### ISSUE TITLE
German version of GASdotto - translation js not loading on gasdotto instance

### ISSUE THREAD

**Issue by jen-do** [madbob/GASdottoNG#61]
Hello,

thanks a lot for fixing things so quickly and for importing the completed German translation to the instances running on the gasdotto.net subdomains.

However, I'm not able to view the changes on our instance (soliorangen): I get a 404 for the de-DE.js

Another translation issue regarding the email notification that is
been send when a new orders of a supplier is opened: The value of the variable
is set to 'nie'(mai) although we defined a closing date of that order.

In the folling comments I add some things I noticed (most of them I already reported via email, but surely, ist's better to place them here).

Best regards,
jenny

**Comment by madbob** [comment]
I didn't receive your email :-\
Anyway you should be able to attach files here: just below the comment box there (should) be the clickable text to do it.

**Comment by jen-do** [comment]
It doesn't seem to support attaching .po files. So I just past it here (sorry, i'm quite new to Github):

`# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-11-17 11:19+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: public/js/gasdotto.js:145 public/js/gasdotto.js:149
msgid "Questa prenotazione esiste già e non può essere ricreata."
msgstr "Diese Vorbestellung existiert schon und kann nicht wiederhergestellt werden."

#: public/js/gasdotto.js:1122 public/js/gasdotto.js:987
msgid "Sei sicuro di voler revocare questo ruolo?"
msgstr "Bist du sicher, dass du diese Rolle widerrufen möchtest?"

#: public/js/gasdotto.js:1599 public/js/gasdotto.js:1443
msgid "Sei sicuro di voler eliminare questo elemento?"
msgstr "Bist du sicher, dass du dieses Element löschen möchtest?"

#: public/js/gasdotto.js:1732 public/js/jquery.dynamictree.js:73
#: public/js/gasdotto.js:1678 public/js/jquery.dynamictree.js:81
msgid "Salvato!"
msgstr "Gespeichert!"

#: public/js/gasdotto.js:1810 public/js/gasdotto.js:1780
msgid "bilanci_ricalcolati.csv"
msgstr "bilanzen_neuberechnet.csv"

#: public/js/gasdotto.js:1829 public/js/gasdotto.js:1799
msgid "Nuova Password"
msgstr "Neues Passwort"

#: public/js/gasdotto.js:1833 public/js/gasdotto.js:1803
msgid "Conferma Password"
msgstr "Passwort bestätigen"

#: public/js/gasdotto.js:1837 public/js/gasdotto.js:1889
#: public/js/gasdotto.js:1807 public/js/gasdotto.js:1863
msgid "Annulla"
msgstr "Löschen"

#: public/js/gasdotto.js:1837 public/js/gasdotto.js:1889
#: public/js/gasdotto.js:1863
msgid "Salva"
msgstr "Speichern"

#: public/js/gasdotto.js:1877 public/js/gasdotto.js:1851
msgid "Indirizzo"
msgstr "Adresse"

#: public/js/gasdotto.js:1881 public/js/gasdotto.js:1855
msgid "Città"
msgstr "Stadt"

#: public/js/gasdotto.js:1885 public/js/gasdotto.js:1859
msgid "CAP"
msgstr "PLZ"

#: public/js/gasdotto.js:2092 public/js/gasdotto.js:2065
msgid "ERRORE"
msgstr "FEHLER"

#: public/js/gasdotto.js:2170 public/js/gasdotto.js:2286
msgid "Invia Mail"
msgstr "Mail verschicken"

#: public/js/gasdotto.js:2176 public/js/gasdotto.js:2292
msgid "Download"
msgstr "Herunterladen"

#: public/js/gasdotto.js:2390 public/js/gasdotto.js:2567
msgid "Tutte le quantità consegnate sono a zero! Vuoi davvero procedere?"
msgstr "Alle Bestellmengen sind auf Null! Willst du wirklich fortfahren?"

#: public/js/gasdotto.js:2426 public/js/gasdotto.js:2603
msgid "Sei sicuro di voler annullare questa prenotazione?"
msgstr "Bist du sicher, dass du diese Vorbestellung löschen möchtest?"

#: public/js/gasdotto.js:1807
msgid "Conferma"
msgstr "Bestätigen"
`
