### ISSUE TITLE
Differing totals when status of order is set to 'delivered'

### ISSUE THREAD

**Issue by jen-do** [madbob/GASdottoNG#63]
We appreciate very much that the system is flexible and that changes can
be made also during the process of ordering and deliveries (e.g. adjusting
the available quantity of a product...). When it comes to accounting I
noticed a detail that might be puzzling for people who order: When a
person has ordered say 20 kilos of oranges, but only received 10 kilos, I,
as an administrator, can manually adjust the amount of delivered oranges
in the system, and set the status to 'delivered' and the price for that product will be
adjusted automatically. However, the total price the orderer should pay
doesn't seem to change.
The new and adjusted total price is only displayed correctly in the user's
profile > accounting (and on the homepage > current credit). But in user's
profile > reservations and in the pdf 'delivery details' a user still
sees the old price without the changes.

**Comment by madbob** [comment]
Fixed in 4857316c3987511232907ba57cdc4d7214c3fec1
