### ISSUE TITLE
Reservations form

### ISSUE THREAD

**Issue by jen-do** [madbob/GASdottoNG#64]
When I fill in the quantity of an article I want to order and immediatly
afterwards hit 'enter' (the current input field being still focused), the
value of the quantity field of the FIRST article in the list is
incremented by 1 (each time I hit 'enter'). So it can be that people order
things unintendedly and without noticing. This only occurs on 'enter',
navigating with tab or mouse works fine.

**Comment by madbob** [comment]
Fixed in commit 9175a6d1dafae06ab66a6f74f6b80d5f7df1177a
