### ISSUE TITLE
Notification sent via e-mail won't be delivered

### ISSUE THREAD

**Issue by SimoneMSR** [madbob/GASdottoNG#68]
Steps to reproduce:
1) log as admin
2) create notification (select users [who have set their email address in profile])
3) flag the 'Send email' toggle
4) save

Expected behaviour: the users receive the email

Actual behaviour: no email received

**Comment by viandanteoscuro** [comment]
I am the same issue, env file is correctly configured. But no emails were sended.

**Comment by SimoneMSR** [comment]
@viandanteoscuro If you go to
Configuration -> Permission -> Admin
Do you see the **Notification management** permission enabled

**Comment by madbob** [comment]
@viandanteoscuro any error logged in storage/logs/ ?

**Comment by viandanteoscuro** [comment]
Solved.
In my case was a bad config parameters in the hosting documentation.

Thanks
