### ISSUE TITLE
Cannot create a product category

### ISSUE THREAD

**Issue by SimoneMSR** [madbob/GASdottoNG#72]
Available categories are:
- 0
- drink
- cosmetic
- fruit
- not specified
- vegetable

It is not possible to extend this list, which is quite limitated.

**Comment by madbob** [comment]
Il tuo utente ha abilitato il permesso "Amministrare le categorie"? Per gli utenti autorizzati, c'e' il tasto "Amministra Categorie" nel pannello dei "Fornitori".
