### ISSUE TITLE
translation support / translating recently added strings

### ISSUE THREAD

**Issue by jen-do** [madbob/GASdottoNG#76]
we would continue working on the german translation as new features and strings are added to the software that should be translated. 
what's the best way to organize that? doing the translation on weblate and nofify you when we completed it?

**Comment by madbob** [comment]
I already update strings on Weblate, and merge translations from the platform, about once a month. Just get a look to [this page](https://hosted.weblate.org/projects/gasdottong/translations/) when you find an untraslated string, eventually some new addiction/modification has been introduced!
