### ISSUE TITLE
installazione su Cloudways - errore 500

### ISSUE THREAD

**Issue by nicobts** [madbob/GASdottoNG#77]
Salve, purtroppo non c'è verso di riuscire a far funzionare l'installazione sul mio server su cloudways. Continuo ad avere un errore server (error 500). Qualcuno sa indicarmi se devo editare alcune impostazioni in particolare affinchè funzioni? 
Ho provato a farlo girare anche in locale (WAMP - apache) e anche in questo caso non c'è verso di farlo funzionare.

Anticipatamente grazie per chi mi risponderà

**Comment by madbob** [comment]
Qui c'e' qualche indicazione
https://www.gasdotto.net/docs/installazione
in particolare relativa alla configurazione della DocumentRoot del web server.

Un errore 500 e' molto generico: potrebbe voler dire che il web server non riesce a scrivere in una delle cartelle (dunque basta cambiare i permessi) o che lo spazio hosting non ha qualcuna delle librerie PHP di sistema richieste. Hai modo di accedere all'error log del servizio hosting, per vedere se dice qualcosa di piu'?

**Comment by nicobts** [comment]
Provato in locale, sembra funzionare correttamente collegandosi al mio db, poi i comandi "php artisan migrate" e "php artisan seed..." mi danno errori.. nel primo caso dice che le tabelle esistono già, nel secondo caso manca la tabella test_deb.users non esiste/mancante. 
ed è questo il messaggio che ottengo:"Oops... Si è verificato un errore...


Gli errori vengono solitamente intercettati e notificati agli sviluppatori.

Se questo dovesse continuare a ripetersi, segnalalo all'indirizzo info@gasdotto.net avendo cura di specificare:

l'istanza su cui stavi lavorando
cosa stavi facendo nel momento in cui si è manifestato
quale utente, fornitore, ordine o prenotazione stavi manipolando


GASdotto è in continua evoluzione... Ma di tanto in tanto ci scappa qualche svista!

".
Sarebbe di enorme aiuto se riuscissi a farlo funzionare intanto in locale e poi mi arrangerei a farlo funzionare sul mio server cloud. Chiedo scusa per la pigrizia, di solito non chiedo e mi metto a sbatterci la testa finchè non ne vengo fuori. Ma visto che siamo connazionali ho azzardato a scriverti.
Riguardo all'errore 500 penso sia un problema di settaggio del webroot dell'app. risolverò in seguito (il mio server è su Cloudways..)

**Comment by madbob** [comment]
Quantomeno il VirtualHost sembra rispondere correttamente, sembrerebbe essere dunque un problema di database. Potrebbe trattarsi del solito annoso problema della compatibilita' con le versioni piu' vecchie di MySQL; ho committato adesso nel repository il fix.

Dunque:
- elimina e ricrea ex-novo il database, vuoto
- preleva l'ultimo aggiornamento del codice dal repository (`git pull`, o scarica l'archivio compresso), oppure applica a mano la correzione riportata nel commit fc990aa30fc10bb25e0a3eab6ecac06293b633cf (ho aggiunto due righe in `code/app/Providers/AppServiceProvider.php`)
- riesegui `php artisan migrate`

**Comment by nicobts** [comment]
Grazie infinite per la pronta risposta, ma php migrate continua ad avere
alcuni problemi..

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was
too long; max key length is 1000 bytes (S
  QL: alter table `order_product` add primary key
`order_product_order_id_product_id_primary`(`order_id`, `product_id
  `))


In PDOStatement.php line 119:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was
too long; max key length is 1000 bytes


In PDOStatement.php line 117:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was
too long; max key length is 1000 bytes

riguardo al fatto che forse è un problema di mysql: la mia attuale versione
è 5.7.23; Ho provato sia con WAMP che con il server di Laravel ma niente..
sempre lo stesso errore..

Il giorno lun 25 feb 2019 alle ore 11:59 Roberto Guido <
notifications@github.com> ha scritto:

**Comment by madbob** [comment]
Questo pero' e' esattamente il problema che dovrebbe essere risolto dal commit sopra citato (si trovano svariati riferimenti online, [tipo questo](https://hdtuto.com/article/laravel-55-1071-specified-key-was-too-long-max-key-length-is-767-bytes)).
Sicuro che nel tuo `code/app/Providers/AppServiceProvider.php` ci sia la riga `Schema::defaultStringLength(191);`?

**Comment by nicobts** [comment]
Si confermo. Non sembra voler funzionare. Se vuoi ti posso dare accesso
all'istanza di Laravel sul mio server tramite ssh e ftp. Ma non vorrei
essere invadente. Vorrei anche capire dove sta il problema sopratuttto..

Grazie,

Nicolas

Il giorno lun 25 feb 2019 alle ore 15:07 Roberto Guido <
notifications@github.com> ha scritto:

**Comment by nicobts** [comment]
Non ci siamo più sentiti ahimè. Mi chiedevo se era possibile trovare una
soluzione rapida in modo semplice o si tratta di un problema più
strutturato a livello profondo.
Chiedo scusa per il disturbo,

Grazie,

Nicolas Bossi

Il giorno mar 26 feb 2019 alle ore 12:49 Nicolas Bossi <
nicolasbossi@gmail.com> ha scritto:

**Comment by madbob** [comment]
Hai ragione, non ho più avuto modo di guardare. Il problema di fondo e' che appoggiandosi ad un generico servizio hosting, senza accesso SSH, diventa tutto molto complicato: installazione delle dipendenze, paths e quant'altro. Motivo percui sul sito viene offerto [un servizio hosting gratuito e gestito](https://www.gasdotto.net/#usage-wrapper), per semplificare la vita a chi non ha un proprio VPS.
La disponibilita' di un pacchetto "drag and drop" destinato agli spazi hosting web e' gia' stata chiesta altrove diverse volte, ma non ho ancora avuto modo di provvedere.
