### ISSUE TITLE
Is it possible to preserve an immutable set of data regarding orders once these orders have been archived?

### ISSUE THREAD

**Issue by jen-do** [madbob/GASdottoNG#79]
I recently noticed that the data of past orders (be it closed, delivered or archived orders) can be manipulated by changes made in the products table (suppliers > products). So when I change the price of a product, the change will not only apply to the current/upcoming order, but to all past and present orders.

As I understand it, the products and users tables form the basis for calculation and allocation of data in the orders table. And this makes total sense to me. However, I was wondering if there is a way to preserve the integrity of data at a certain point in time, e.g. when the order is set to 'archived'.
So the archive would still reflect the past order correctly and not change each time a price is adjusted.
Right now, we're exporting the provided files and thus store our archive offline. Is it possible to find a solution for that within the system?

**Comment by madbob** [comment]
Actually the informations about products in the suppliers' list are not preserved in time, but informations (including prices) about actually shipped products are saved attached to the reservations. This has been a deliberated choice, as with a previous version of GASdotto we observed that duplicating the products to maintain their status through time resulted in an uncontrolled growth of the database.

If your concern is about displaying a correct rappresentation of the order even after its archiviation, I can provide a different view using the effective preserved data stored with reservations.

**Comment by jen-do** [comment]
Very sorry for the delay of my answer. If you can find a solution to to display that represention of the archived data, that's not so laborious, that would be great!
