### ISSUE TITLE
Personalizzazione report "Dettaglio Consegne"

### ISSUE THREAD

**Issue by seldon** [madbob/GASdottoNG#82]
Nella sezione _Ordini_, è possibile generare un prospetto riassuntivo delle prenotazioni relative ad un determinato ordine, divise per gasista (premendo il bottone "Dettaglio Consegne").

Al fine di agevolare le operazioni di distribuzione dell'ordine, sarebbe utile poter configurare la struttura delle tabelle presenti nel file PDF - ad esempio aggiungendo campi come "codice prodotto" o "numero confezioni" - come avviene per il report _Riassunto Prodotti Ordinati_

Inoltre, sarebbe utile avere la possibilità di generare un report in formato CSV.

**Comment by pcdevoti** [comment]
Spostato nella colonna TODO del progetto "In Progress"
