### ISSUE TITLE
Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by viandanteoscuro** [madbob/GASdottoNG#83]
Salve,
Facendo l'installazione a mano ho questo errore sulla migration:

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `order_product` add primary key `  
  order_product_order_id_product_id_primary`(`order_id`, `product_id`))

Il mio db è un MariaDB 10.2.25

Posso risolvere mettendo una dimensione massima della stringa, ma non vorrei che ciò causi qualche problema al sistema.

Altrimenti ci sono altre soluzioni?
Grazie mille
Saluti

**Comment by madbob** [comment]
Questo avrebbe gia' dovuto essere sistemato con questo commit
https://github.com/madbob/GASdottoNG/commit/fc990aa30fc10bb25e0a3eab6ecac06293b633cf#diff-e9887c6d31e568b535ca79b2494ea998

Qua ci sono altri suggerimenti su come aggirare il problema: https://github.com/laravel/framework/issues/24711

**Comment by viandanteoscuro** [comment]
Grazie per la risposta, purtroppo il problema ce l'ho avuto scaricando l'ultima versione, quindi probabilmente è ritornato.
Anche mettendo utf8, e non utf8m4, non si risolve.
Al momento non ho messo come chiave la coppia order_id e product_id... perderò un po' in prestazioni, ma per renderli chiave dovrei abbassare la lunghezza dei varchar a 150.

**Comment by madbob** [comment]
Ho appena provato una migrazione ex-novo su MariaDB 10.1.40, senza alterare la configurazione presente anche sul repository, ma è andata a buon fine.
Se vuoi modificare la lunghezza di default delle stringhe per lo schema, puoi modificare la riga `Schema::defaultStringLength(NUMERO_CHE_VUOI);` in `code/app/Providers/AppServiceProvider.php` prima di procedere con la migrazione.

**Comment by viandanteoscuro** [comment]
Probabilmente allora è qualche configurazione del servizio di hosting...
Perfetto grazie allora, chiudo
