### ISSUE TITLE
Contabilità errore 500

### ISSUE THREAD

**Issue by viandanteoscuro** [madbob/GASdottoNG#84]
Salve,

Accedendo alla pagina contabilità ottengo errore 500.
Nei log di laravel ho questo errore:

production.ERROR: class_uses(): Class App\error does not exist and could not be loaded (View: /public_html/GASdottoNG/code/resources/views/movementtypes/base-edit.blade.php)

Grazie mille.

Saluti

Massimo

**Comment by madbob** [comment]
Posso intuire che sia finito qualcosa di errato nel database.
Se sul DB esegui
`SELECT * FROM movements where target_type like '%error%'`
oppure
`SELECT * FROM movement_types where target_type like '%error%'`
ti da dei risultati?

**Comment by viandanteoscuro** [comment]
Entrambe le query ritornano 0 risultati

**Comment by viandanteoscuro** [comment]
Avrei bisogno di una soluzione, visto che mi chiudono delle campagne oggi e senza contabilità funzionante non riesco a far nulla...

**Comment by madbob** [comment]
Dentro la cartella `code/app` c'e' forse un qualche file che si chiama "error", o comunque non Qualcosa.php (oltre alle cartelle)?

**Comment by madbob** [comment]
Questa modifica dovrebbe permettere di aggirare il problema: https://github.com/madbob/GASdottoNG/commit/dacae60921a1429561db16ee4a46d6a705c38ea5

**Comment by viandanteoscuro** [comment]
Ero arrivato anche io allo stesso file che dava errore... solo che non avevo tempo per sistemare...
Il problema è che ho fatto pull e poi update e install come indichi nella guida... e ora non va più nulla... è venuto fuori un errore di escapeshellarg disabilitata e versione di Carbon deprecata e il sito è morto...

**Comment by madbob** [comment]
L'"escapeshellarg disabilitata" potrebbe essere un problema della configurazione PHP: https://stackoverflow.com/questions/32476556/composer-escapeshellarg-has-been-disabled-for-security-reasons
I log (quelli in `code/storage/logs/`, ma anche del web server) dicono qualcosa di piu'?

**Comment by viandanteoscuro** [comment]
Si lo so, il problema è che è un servizio di hosting condiviso, non me la abilitano e pare che non possa usare un php.ini custom... e ora sul sito ho pagina bianca... nessun errore, semplicemente pagina bianca...
