### ISSUE TITLE
Prenotazione per gli altri

### ISSUE THREAD

**Issue by viandanteoscuro** [madbob/GASdottoNG#85]
Buongiorno,
Cosa devo abilitare per rendere possibile la "Prenotazione per gli altri"?
Posso scegliere l'utente, ma vedo solo quello che eventualmente ha già prenotato, non posso aggiungere altro.

Grazie mille

Saluti
MAssimo

**Comment by madbob** [comment]
Se l'ordine e' gia' consegnato la prenotazione non puo' essere modificata. Hai provato a vedere una "prenotazione per gli altri" di un ordine ancora aperto?

**Comment by pcdevoti** [comment]
Aggiungo che i casi sono 3:

*	Se lo stato dell’Ordine è “Prenotazioni aperte” dovrebbe funzionare la “Prenotazione per gli altri”
*	Se lo stato dell’Ordine è “Prenotazioni chiuse” bisogna usare la funzione “Aggiungi/Modifica prenotazione”
*	Se lo stato dell’Ordine è “Consegnato” non è più possibile modificare le prenotazioni

 

Saluti,

Pier Carlo

 

Da: Roberto Guido <notifications@github.com> 
Inviato: lunedì 29 luglio 2019 11:57
A: madbob/GASdottoNG <GASdottoNG@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: Re: [madbob/GASdottoNG] Prenotazione per gli altri (#85)

 

Se l'ordine e' gia' consegnato la prenotazione non puo' essere modificata. Hai provato a vedere una "prenotazione per gli altri" di un ordine ancora aperto?

**Comment by viandanteoscuro** [comment]
Salve,
In realtà la prenotazione è aperta... ma non mi fa prenotare per altri.

**Comment by pcdevoti** [comment]
Possiamo sentirci via telefono o skype in serata?

Pier Carlo

Cell 340 338 2641

Skype piercarlo.devoti

 

Da: viandanteoscuro <notifications@github.com> 
Inviato: lunedì 29 luglio 2019 23:08
A: madbob/GASdottoNG <GASdottoNG@noreply.github.com>
Cc: pcdevoti <piercarlo.devoti@gmail.com>; Comment <comment@noreply.github.com>
Oggetto: Re: [madbob/GASdottoNG] Prenotazione per gli altri (#85)

 

Salve,
In realtà la prenotazione è aperta... ma non mi fa prenotare per altri.

**Comment by viandanteoscuro** [comment]
Salve,
Ho ancora questo problema, puoi verificare?
Grazie mille
Saluti

**Comment by viandanteoscuro** [comment]
Penso di aver trovato l'inghippo.
Nel controller BookingUser, nel metodo show, c'è questo check:

if (!is_null($request->user()->suspended))

Che è sempre vera perchè la colonna suspended della tabella users è di tipo tinyint(1) con default a 0 e non null...

Ho risolto mettento il testo su true/false

if ($request->user()->suspended)

**Comment by madbob** [comment]
@viandanteoscuro giustissima osservazione, anche se da qualche tempo il booleano `suspended` e' stato sostituito da una data `suspended_at` che effettivamente puo' essere `null`. Ho modificato l'accesso alla variabile giusta in fase di test.
