### ISSUE TITLE
aliquota dell'IVA e fatture per utenti

### ISSUE THREAD

**Issue by jen-do** [madbob/GASdottoNG#92]
The system already provides the ability to edit and assign IVA rates to products. What I could not find out so far is if there are any active operations based on these assigned values. Like calculate the total IVA of an order or calculate the IVA included in an individual order of a user.

Since this year we're bound to make out an invoice for every person who participates in an order. The invoice should also contain the IVA included. I created a crazy excel chart that's doing all the calculations based on the tabella complessiva prodotti.

Are there any plans to integrate a feature like this into GASdotto? 
Or would it be possible add an input field to the products editor that contains the amount of IVA in €  (not percentage) for a specific product. And could this be included in the tabella complessiva next to the column totale prezzo, transporto or sconto?

**Comment by madbob** [comment]
Actually, it is already managed.

Configurations -> Accounting -> Enable Invoices Generation -> input your fiscal details -> Save
From here, for every shipping it is generated an invoice you can retrieve under
Accounting -> Invoices
with total cost and separated VAT.

Don't confuse this function with "Load new invoice" (under the Accounting panel): that is used to load the suppliers' invoices and match it with the actual shippings registered on the system (including separated VAT sums).
