### ISSUE TITLE
PHP error running latest git code

### ISSUE THREAD

**Issue by Polve** [madbob/GASdottoNG#95]
ho installato il programma clonando master (7247513844a8d1e35fd8c854a9c3c3c3f6c9f067) ma ottengo questo errore che non riesco ad interpretare quando cerco di eseguire index:

PHP Fatal error:  Uncaught ErrorException: file_put_contents(/web/GASdottoNG/code/storage/framework/views/0fdf9ef0560507ba72dafc56f04b01b125f0369b.php): failed to open stream: Permission denied in /web/GASdottoNG/code/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/web/GASdottoNG...', 122, Array)\n#1 /web/GASdottoNG/code/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/web/GASdottoNG...', '<!DOCTYPE html>...', 0)\n#2 /web/GASdottoNG/code/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(122): Illuminate\\Filesystem\\Filesystem->put('/web/GASdottoNG...', '<!DOCTYPE html>...')\n#3 /web/GASdottoNG/code/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\\View\\Compilers\\BladeCompiler->compile('/web/GASdottoNG...')\n#4 /web/GASdottoNG/code/vendor/laravel/framework/src/Illuminate/View/View.php( in /web/GASdottoNG/code/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 122

**Comment by Polve** [comment]
uso debian buster con php 7.3 e mariadb 10.3

**Comment by madbob** [comment]
L'errore è abbastanza eloquente: "Permission denied".
Devi dare permessi di scrittura al web server, tipo con
`chown -R www-data:www-data /web/GASdottoNG/code/`

**Comment by Polve** [comment]
ok, chiedo venia, avevo visto il permission denied ma pensavo fosse un problema di lettura, non scrittura.

Ora l'errore è andato ma mi dice che non trova /login, vedo che su nginx dici di configurare:

    location / {
        try_files   $uri $uri/ /index.php?$query_string;
    }

Ma su apache non c'è nulla di simile, non bisogna mettere qualcosa?

**Comment by madbob** [comment]
Dovrebbe essere sufficiente abilitare gli .htaccess nella cartella desiderata, qui trovi qualche indicazione: https://www.howtoforge.com/tutorial/install-laravel-on-ubuntu-for-apache/#configuring-apache

**Comment by Polve** [comment]
ok perfetto, avevo impostato male l'AllowOverride.
Grazie per il pronto supporto.
